#pragma config(Motor,  motor1,          M1,            tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor7,          M2,            tmotorVexIQ, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
int MaxSpeed = 127;
task main()
{

	while(true)
	{

		if (getJoystickValue(ChA) > 10)
			setMotorSpeed(M1, MaxSpeed);
	if (getJoystickValue(ChA) < -10)
			setMotorSpeed(M1, -MaxSpeed);
	if (getJoystickValue(ChD) > 10)
			setMotorSpeed(M2, MaxSpeed);
	if (getJoystickValue(ChD) < -10)
			setMotorSpeed(M2, -MaxSpeed);
	else
	{
	setMotorSpeed(M1, 0);
	setMotorSpeed(M2, 0);
}

	}


}
