#pragma config(Sensor, port2,  Sonar,          sensorVexIQ_Distance)
#pragma config(Sensor, port3,  Colors,         sensorVexIQ_ColorHue)
#pragma config(Sensor, port4,  Gyro,           sensorVexIQ_Gyro)
#pragma config(Sensor, port5,  LEDM,           sensorVexIQ_LED)
#pragma config(Sensor, port8,  BumberL,        sensorVexIQ_Touch)
#pragma config(Sensor, port9,  BumperR,        sensorVexIQ_Touch)
#pragma config(Motor,  motor1,          MotorL,        tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor6,          MotorR,        tmotorVexIQ, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
task main()
{
	resetGyro(Gyro);
	while(true)
	{



		setMotorTarget(motor1, 1000, 127);
		setMotorTarget(motor6, 1000, 127);//makes go for 1000
		wait1Msec(10000);
	while(getGyroDegrees(Gyro) < 90)
		{
			setMotorSpeed(motor1, -25);
			setMotorSpeed(motor6, 25);
		}
		setMotorTarget(motor1, 1000, 127);
		setMotorTarget(motor6, 1000, 127);//makes go for 1000
		wait1Msec(10000);
		while(getGyroDegrees(Gyro) < 180)
		{
			setMotorSpeed(motor1, -25);
			setMotorSpeed(motor6, 25);
		}
		setMotorTarget(motor1, 1000, 127);
		setMotorTarget(motor6, 1000, 127);//makes go for 1000
		wait1Msec(10000);
		while(getGyroDegrees(Gyro) < 270)
		{
			setMotorSpeed(motor1, -25);
			setMotorSpeed(motor6, 25);
		}
		setMotorTarget(motor1, 1000, 127);
		setMotorTarget(motor6, 1000, 127);//makes go for 1000
		wait1Msec(10000);
		while(getGyroDegrees(Gyro) < 360)
		{
			setMotorSpeed(motor1, -25);
			setMotorSpeed(motor6, 25);
		}





	}
}
