#pragma config(Sensor, port10, Color,          sensorVexIQ_ColorHue)
#pragma config(Motor,  motor1,          MotorR,        tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor2,          MotorL,        tmotorVexIQ, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int Launch = 0;
int Count = 0;
int Con = true;
task main()
{
	resetMotorEncoder(MotorR);

	while(true)
	{
		if (Con == true)
			Count +=1;

		if (Count == 10000)
		{
			Con = false;
			setMotorTarget(MotorR,60,100);

			Launch = 1;
		}
		if (Launch == 1 && getColorHue(Color)== 70)
		{

			Launch = 0;
			setMotorTarget(MotorR,70,100);

			sleep(1000);
			setMotorTarget(MotorR,360,100);

			resetMotorEncoder(MotorR);
			Con = true;
		}


	}

}
