#pragma config(Motor,  port1,           Arm2,          tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           LW2,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           RW1,           tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           RW2,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           Ele,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           Laun,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           Wrist1,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           Wrist2,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           LW1,           tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          Arm1,          tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int Thresh = 10;
int MaxS = 127;
int MaxR = MaxS *-1;
int Stop = 0;



void Controller1 () {
	if (getJoystickValue(Ch2) > Thresh) {
		motor [LW1] = MaxR;
		motor [LW2] = MaxR;

		} else if (getJoystickValue(Ch2) < Thresh*-1) {
		motor [LW1] = MaxS;
		motor [LW2] = MaxS;

		} else {
		motor [LW1] = Stop;
		motor [LW2] = Stop;

	}

	if (getJoystickValue(Ch3) > Thresh) {
		motor [RW1] = MaxS;
		motor [RW2] = MaxS;

		} else if (getJoystickValue(Ch3) < Thresh*-1) {
		motor [RW1] = MaxR;
		motor [RW2] = MaxR;

		} else {
		motor [RW1] = Stop;
		motor [RW2] = Stop;
	}

	if (getJoystickValue(Btn6D) == 1 )
		motor [Ele] = 60;
	else
		motor [Ele] = Stop;

	if (getJoystickValue(Btn5D) == 1 )
		motor [Laun] = MaxS;
	else
		motor [Laun] = Stop;
}



//
//
//Controller2
//
//



void Controller2 () {


	if (getJoystickValue(Btn5DXmtr2) == 1 ) {
		motor [Arm1] = MaxS;
		motor [Arm2] = MaxS;
		} else if (getJoystickValue(Btn5UXmtr2) == 1) {
		motor [Arm1] = MaxR;
		motor [Arm2] = MaxR;

		} else {
		motor [Arm1] = Stop;
		motor [Arm2] = Stop;
	}

	if (getJoystickValue(Ch2Xmtr2) > Thresh)
		motor [Wrist1] = MaxS;

	else if (getJoystickValue(Ch2Xmtr2) < Thresh*-1)
		motor [Wrist1] = MaxR;

	else
		motor [Wrist1] = Stop;


	if (getJoystickValue(Ch4Xmtr2) > Thresh)
		motor [Wrist2] = MaxS;

	else if (getJoystickValue(Ch4Xmtr2) < Thresh*-1)
		motor [Wrist2] = MaxR;

	else
		motor [Wrist2] = Stop;
}
//
//
//Actual Program
//
//


task main()
{
	while(true)
	{
Controller1();
Controller2();

	}
}
