#pragma config(Motor,  motor1,          Motor1,        tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor7,          Motor2,        tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor8,          Motor4,        tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor9,          Motor3,        tmotorVexIQ, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true)
	{
		if (getJoystickValue(BtnFUp) == 1)
		{
			setMotorSpeed(motor1, 75);
			setMotorSpeed(motor7, 75);
			setMotorSpeed(motor6, 75);
			setMotorSpeed(motor8, 75);
		}
		else if (getJoystickValue(BtnFDown) == 1)
		{
			setMotorSpeed(motor1, -75);
			setMotorSpeed(motor7, -75);
			setMotorSpeed(motor6, -75);
			setMotorSpeed(motor8, -75);
		} else
		{
			setMotorSpeed(motor1, 0);
			setMotorSpeed(motor7, 0);
			setMotorSpeed(motor8, 0);
			setMotorSpeed(motor6, 0);
		}
	}


}
