#pragma config(Motor,  port1,           M1,            tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int Start = 0;
int MaxS = 127;
task main()
{
	Start = 0;
while(true)
{

motor [M1] = MaxS;


Start = Start + 1;

}
wait1Msec(10000);
}
