#pragma config(Sensor, port6,  Button,         sensorVexIQ_Touch)
#pragma config(Sensor, port7,  Num1,           sensorVexIQ_LED)
#pragma config(Sensor, port8,  Num2,           sensorVexIQ_LED)
#pragma config(Sensor, port9,  Num3,           sensorVexIQ_LED)
#pragma config(Sensor, port11, Distance,       sensorVexIQ_Distance)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void Del () {
	displayTextLine(1,"  ");
	displayTextLine(2,"  ");
	displayTextLine(3,"  ");
	displayTextLine(4,"  ");
	displayTextLine(5,"  ");
	sleep(2000);

}

//while(N1 == 0)                           This is how you pick choices
//	{
//		setTouchLEDRGB(Num1,0,255,0);
//		setTouchLEDRGB(Num2,0,0,255);
//		setTouchLEDRGB(Num3,255,0,0);

//		if (getTouchLEDValue(Num1)== 1) {
//			N1 = N1 +1;
//		}
//		if (getTouchLEDValue(Num2)== 1) {
//			N1 = N1 +2;
//		}
//		if (getTouchLEDValue(Num3)== 1) {
//			N1 = N1 +3;
//		}
//}
int N1;
int Hits;
int Berry = 0;
int Count;
int Final = 0;
int Ogre = 0;
int Touched = 0;
int Dist = 0;
task main()
{
	N1 = 1;
	setDistanceMaxRange(Distance, 300);
	Del();
	//
	//
	//First path!!!!!
	//
	//
	if (N1 == 1)
	{
		N1 = 0;

		displayTextLine(1,"You've entered the");
		sleep(1000);
		displayTextLine(2,"First Path");
		sleep(1000);
		displayTextLine(3,"As you walk, the");
		sleep(1000);
		displayTextLine(4,"Further and Further ");
		sleep(1000);
		displayTextLine(5,"You go you notice");
		sleep(1500);

		Del();

		displayTextLine(1,"A abundance of");
		sleep(1000);
		displayTextLine(2,"Wildlife.");
		sleep(1000);
		displayTextLine(3,"And the path opens");
		sleep(1000);
		displayTextLine(4,"To a wild grand");
		sleep(1000);
		displayTextLine(5,"Field");
		sleep(1500);

		Del();

		displayTextLine(1,"You come across");
		sleep(1000);
		displayTextLine(2,"What appears to be");
		sleep(1000);
		displayTextLine(3,"A strange kind of");
		sleep(1000);
		displayTextLine(4,"Grape vine growing");
		sleep(1000);
		displayTextLine(5,"From the ground");
		sleep(1500);

		Del();

		displayTextLine(1,"Do you");
		sleep(1000);
		displayTextLine(2,"");
		sleep(1000);
		displayTextLine(3,"Pick it up(Green)");
		sleep(1000);
		displayTextLine(4,"Eat it    (Blue)");
		sleep(1000);
		displayTextLine(5,"Leave it  (Red)");
		sleep(1500);

		Berry = 0;
		N1 = 0;
		//
		//Grab eat or leave berry
		//
		while(N1 == 0)
		{
			setTouchLEDRGB(Num1,0,255,0);
			setTouchLEDRGB(Num2,0,0,255);
			setTouchLEDRGB(Num3,255,0,0);

			if (getTouchLEDValue(Num1)== 1)
			{
				N1 = N1 +1;
				Berry = +1;
			}
			if (getTouchLEDValue(Num2)== 1)
				N1 = N1 +2;

			if (getTouchLEDValue(Num3)== 1)
				N1 = N1 +3;

		}
		//
		//Leave the Berry behind
		//
		if (N1 == 3)
		{
			Del();

			displayTextLine(1,"You decide to");
			sleep(1000);
			displayTextLine(2,"Leave the berry");
			sleep(1000);
			displayTextLine(3,"Behind and");
			sleep(1000);
			displayTextLine(4,"Continue on the");
			sleep(1000);
			displayTextLine(5,"Path");
			sleep(1500);

			N1 = 1;
		}
		//
		//Keep berry for later
		//
		if (N1 == 1)
		{
			if (Berry == 1)
			{
				Del();

				displayTextLine(1,"You reach for the");
				sleep(1000);
				displayTextLine(2,"Berry");
				sleep(1000);
				displayTextLine(3,"");
				sleep(1000);
				displayTextLine(4,"Reach your hand out");
				sleep(1000);
				displayTextLine(5,"20 cm above sensor ");
				sleep(1500);

				Del();

				Touched = 0;
				//
				//You reach out
				//
				while(Touched == 0)
				{
					if (getDistanceValue(Distance) < 230 && getDistanceValue(Distance) > 180)
					{
						Touched = Touched +1;
					}
					Dist = getDistanceValue(Distance);

					setTouchLEDRGB(Num1,0,255,0);
					setTouchLEDRGB(Num2,0,0,255);
					setTouchLEDRGB(Num3,255,0,0);
					displayTextLine(3,"Distance: %d",Dist);
					sleep(10);

				}
				sleep(100);

				Del();

				displayTextLine(1,"You grab the berry");
				sleep(1000);
				displayTextLine(2,"And put it in your");
				sleep(1000);
				displayTextLine(3,"Pocket for later.");
				sleep(1000);
				displayTextLine(4,"You continue through");
				sleep(1000);
				displayTextLine(5,"");
				sleep(1500);
			}

			Del();

			displayTextLine(1,"As you continue you");
			sleep(1000);
			displayTextLine(2,"See a sleeping figure");
			sleep(1000);
			displayTextLine(3,"In the distance.");
			sleep(1000);
			displayTextLine(4,"As you get closer you");
			sleep(1000);
			displayTextLine(5,"Find a sleeping");
			sleep(1500);

			Del();

			displayTextLine(1,"Dragon in a open field");
			sleep(1000);
			displayTextLine(2,"As you look a deer runs");
			sleep(1000);
			displayTextLine(3,"Past the dragon who");
			sleep(1000);
			displayTextLine(4,"Wakes it up and kills");
			sleep(1000);
			displayTextLine(5,"Immediately...!");
			sleep(3500);

			Del();

			displayTextLine(1,"It dosent see you so");
			sleep(1000);
			displayTextLine(2,"it goes back to a");
			sleep(1000);
			displayTextLine(3,"Shallow slumber");
			sleep(100);
			displayTextLine(4,"");
			sleep(100);
			displayTextLine(5,"");
			sleep(300);

			Del();

			displayTextLine(1,"What do you do?");
			sleep(1000);
			displayTextLine(2,"");
			sleep(1000);
			displayTextLine(3,"Sneak around(Green)");
			sleep(1000);
			displayTextLine(4,"Charge at it(Blue)");
			sleep(1000);
			if (Berry == 1)
			{
				displayTextLine(5,"Throw Berry (Red)");
				sleep(1500);
			} else
			{
				displayTextLine(5,"");
				sleep(1500);
			}

			N1 = 0;

			//
			//Throw berry sneak or fight Dragon
			//

			while(N1 == 0)
			{
				setTouchLEDRGB(Num1,0,255,0);
				setTouchLEDRGB(Num2,0,0,255);
				setTouchLEDRGB(Num3,255,0,0);

				if (getTouchLEDValue(Num1)== 1)
					N1 = N1 +1;

				if (getTouchLEDValue(Num2)== 1)
					N1 = N1 +2;

				if (Berry >= 1) {
					if (getTouchLEDValue(Num3)== 1)
						N1 = N1 +3;
				}

			}

			if (N1 == 1)
			{
				//
				//Sneak around the big scary dragon
				//

				Del();

				displayTextLine(1,"You start to sneak");
				sleep(1000);
				displayTextLine(2,"Around the dragon");
				sleep(1000);
				displayTextLine(3,"And need to be 15m");
				sleep(1000);
				displayTextLine(4,"Away from it so it");
				sleep(1000);
				displayTextLine(5,"Dosent wake up");
				sleep(3500);

				Del();

				displayTextLine(1,"Hold your hand");
				sleep(1000);
				displayTextLine(2,"15cm above sensor");
				sleep(1000);
				displayTextLine(3,"To stay away");
				sleep(100);
				displayTextLine(4,"From the dragon");
				sleep(100);
				displayTextLine(5,"");
				sleep(300);

				Del();
				Touched = 0;
				Dist = 0;
				//
				//Reach out to sneakget
				//
				while(Touched == 0)
				{
					if (getDistanceValue(Distance) < 170 && getDistanceValue(Distance) > 135)
					{
						Touched = Touched +1;
					}
					Dist = getDistanceValue(Distance);
					setTouchLEDRGB(Num1,0,255,0);
					setTouchLEDRGB(Num2,0,0,255);
					setTouchLEDRGB(Num3,255,0,0);
					displayTextLine(3,"Distance: %d",Dist);
					sleep(10);
					Count = Count +1;
				}
				sleep(1000);
				if (Touched == 1)
				{
					Del();

					displayTextLine(1,"You walked around");
					sleep(1000);
					displayTextLine(2,"The sleeping dragon");
					sleep(1000);
					displayTextLine(3,"And continue on the");
					sleep(1000);
					displayTextLine(4,"Path   The field");
					sleep(1000);
					displayTextLine(5,"Soon comes to a close");

					Del();

					displayTextLine(1,"Go to program The End");
					sleep(1000);
					sleep(2000000000);
					N1 = 0;
					Final = 1;
				}
			}
			if (N1 == 2)
			{
				//
				//Charge at the big scary blood thirsty dragon and hopefully survive ;P
				//

				Del();

				displayTextLine(1,"You charge and yell");
				sleep(1000);
				displayTextLine(2,"At the dragon");
				sleep(1000);
				displayTextLine(3,"");
				sleep(1000);
				displayTextLine(4,"He roasts you");
				sleep(1000);
				displayTextLine(5,"And eats you");
				sleep(3500);

				Del();

				displayTextLine(1,"Like a pogo");
				sleep(1000);
				displayTextLine(2,"");
				sleep(100);
				displayTextLine(3,"");
				sleep(100);
				displayTextLine(4,"");
				sleep(100);
				displayTextLine(5,"");
				sleep(350);

				Del();

				displayTextLine(1,"   Congrats!");
				sleep(1000);
				displayTextLine(2,"You died! GAME OVER!");
				sleep(1000);
				displayTextLine(3,"Think again before");
				sleep(1000);
				displayTextLine(4,"Charging at a dragon");
				sleep(1000);
				displayTextLine(5,"");
				sleep(350000000);
				N1 = 0;
			}
			if (N1 == 3)
			{
				//
				//Throw the berrys at the big scary dragon
				//

				Del();

				displayTextLine(1,"You throw the");
				sleep(1000);
				displayTextLine(2,"Berry at the Dragon");
				sleep(1000);
				displayTextLine(3,"It eats it and dies");
				sleep(1000);
				displayTextLine(4,"That was... easy...");
				sleep(1000);
				displayTextLine(5,"You continue on the");
				sleep(2000);

				Del();

				displayTextLine(1,"Path");
				sleep(1000);
				displayTextLine(2,"");
				sleep(1000);
				displayTextLine(3,"Eventually the field");
				sleep(1000);
				displayTextLine(4,"Comes to a close");
				sleep(1000);
				displayTextLine(5,"Go to program The END");
				sleep(2000000000);
				N1 = 0;
				Final = 1;
			}
		}
		//
		//Eat the berry and possibly die ;P
		//
		if (N1 == 2)
		{
			//
			//Reach out for berry 20 cm to eat it
			//
			Del();

			displayTextLine(1,"You reach for the");
			sleep(1000);
			displayTextLine(2,"Berry");
			sleep(1000);
			displayTextLine(3,"");
			sleep(1000);
			displayTextLine(4,"Reach your hand out");
			sleep(1000);
			displayTextLine(5,"20 cm above sensor ");
			sleep(1500);

			Del();
			Touched = 0;
			Dist = 0;
			//
			//You reach out
			//
			while(Touched == 0)
			{
				if (getDistanceValue(Distance) < 230 && getDistanceValue(Distance) > 180)
				{
					Touched = Touched +1;
				}
				Dist = getDistanceValue(Distance);
				setTouchLEDRGB(Num1,0,255,0);
				setTouchLEDRGB(Num2,0,0,255);
				setTouchLEDRGB(Num3,255,0,0);
				displayTextLine(3,"Distance: %d",Dist);

			}
			sleep(100);
			Del();

			displayTextLine(1,"You grab the berry");
			sleep(1000);
			displayTextLine(2,"And start eating it");
			sleep(1000);
			displayTextLine(3,"You instantly die");
			sleep(1000);
			displayTextLine(4,"Due to it being");
			sleep(1000);
			displayTextLine(5,"Poisonous...");
			sleep(1500);

			Del();

			displayTextLine(1,"     Good Job");
			sleep(1000);
			displayTextLine(2,"Congratualations");
			sleep(1000);
			displayTextLine(3,"You died that was");
			sleep(1000);
			displayTextLine(4,"Not a good idea..");
			sleep(1000);
			displayTextLine(5,"GAME OVER!!!");
			sleep(150000000000000);
			N1 = 0;

			//
			//Game over cause of death (Being dumb and eating something you dont know is safe to eat)
			//

		}

	}
	Hits = 0;
	Count = 0;

}
