#pragma config(Sensor, port6,  Button,         sensorVexIQ_Touch)
#pragma config(Sensor, port7,  Num1,           sensorVexIQ_LED)
#pragma config(Sensor, port8,  Num2,           sensorVexIQ_LED)
#pragma config(Sensor, port9,  Num3,           sensorVexIQ_LED)
#pragma config(Sensor, port11, Distance,       sensorVexIQ_Distance)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void Del () {
	displayTextLine(1," ");
	displayTextLine(2," ");
	displayTextLine(3," ");
	displayTextLine(4," ");
	displayTextLine(5," ");
	sleep(2000);

}
int N1 = 0;
int Manticore = 0;
int Points = 0;
int Count = 0;
int Final = 0;
int CL = 0;
int Troll = 0;
int Touch = 0;
task main()
{
	setTouchLEDRGB(Num1,0,255,0);
	setTouchLEDRGB(Num2,0,0,255);
	setTouchLEDRGB(Num3,255,0,0);

	N1 = 0;

	Del();

	displayTextLine(1,"Once you enter the");
	sleep(1000);
	displayTextLine(2,"Path the smell gets");
	sleep(1000);
	displayTextLine(3,"Stronger");
	sleep(1000);
	displayTextLine(4,"Eventually you find");
	sleep(1000);
	displayTextLine(5,"The source of the");
	sleep(1500);

	Del();

	displayTextLine(1,"Smell ");
	sleep(1000);
	displayTextLine(2,"");
	sleep(1000);
	displayTextLine(3,"Its acid ");
	sleep(1000);
	displayTextLine(4,"Where the floor");
	sleep(1000);
	displayTextLine(5,"Should be is Acid");
	sleep(1500);

	Del();

	displayTextLine(1,"With small stepping");
	sleep(1000);
	displayTextLine(2,"Stones to get accross");
	sleep(1000);
	displayTextLine(3,"");
	sleep(100);
	displayTextLine(4,"");
	sleep(100);
	displayTextLine(5,"");
	sleep(150);

	Del();

	displayTextLine(1,"What will you do?");
	sleep(1000);
	displayTextLine(2,"");
	sleep(1000);
	displayTextLine(3,"Turn around(Green)");
	sleep(1000);
	displayTextLine(4,"Continue(Blue)");
	sleep(1000);
	displayTextLine(5,"Win the Game(Red)");
	sleep(150);

	N1 = 0;
	//
	//Go other way or continue through acid
	//
	while(N1 == 0)
	{
		setTouchLEDRGB(Num1,0,255,0);
		setTouchLEDRGB(Num2,0,0,255);
		setTouchLEDRGB(Num3,255,0,0);

		if (getTouchLEDValue(Num1)== 1)
			N1 = N1 +1;

		if (getTouchLEDValue(Num2)== 1)
			N1 = N1 +2;


		if (getTouchLEDValue(Num3)== 1)
		{
			N1 = N1 +2;
			Troll = 1;
		}

	}
	//
	//Turn Around
	//
	if (N1 == 1)
	{

		Del();

		displayTextLine(1,"On your way back");
		sleep(1000);
		displayTextLine(2,"The path crumbles");
		sleep(1000);
		displayTextLine(3,"And you falllll");
		sleep(1000);
		displayTextLine(4,"");
		sleep(1000);
		displayTextLine(5,"");
		sleep(1500);

		Del();

		Del();

		displayTextLine(1," GAME OVER!");
		sleep(1000);
		displayTextLine(2,"You died");
		sleep(1000);
		displayTextLine(3,"BAD CHOICE");
		sleep(1000);
		displayTextLine(4,"Try again");
		sleep(1000);
		displayTextLine(5,"");
		sleep(150000000000000000000000);

	}
	//
	//Continue on PATH
	//
	if (N1 == 2)
	{
		N1 = 0;
		if (Troll == 1)
		{
			Del();

			displayTextLine(1,"LOL, LMAO");
			sleep(1000);
			displayTextLine(2,"You think we will");
			sleep(1000);
			displayTextLine(3,"Just give you the");
			sleep(1000);
			displayTextLine(4,"Win? Continue the");
			sleep(1000);
			displayTextLine(5,"Game");
			sleep(1500);

			N1 = 0;
		}
		Del();

		displayTextLine(1,"The Path starts");
		sleep(1000);
		displayTextLine(2,"Crumbling behind you");
		sleep(1000);
		displayTextLine(3,"Start jumping");
		sleep(1000);
		displayTextLine(4,"To the stones");
		sleep(1000);
		displayTextLine(5,"And don't stand");
		sleep(1500);

		Del();

		displayTextLine(1,"On them for too");
		sleep(1000);
		displayTextLine(2,"Long or they crumble");
		sleep(1000);
		displayTextLine(3,"You have 5 seconds");
		sleep(1000);
		displayTextLine(4,"Per rock");
		sleep(1000);
		displayTextLine(5,"Click on brown LED");
		sleep(1500);

		N1 = 0;
		Touch = 0;
		Count = 0;
		//
		//Jump 1 for rocks
		//
		while(Count <= 400 || Touch == 0)
		{

			setTouchLEDRGB(Num1,160,70,0);
			setTouchLEDRGB(Num2,255,255,0);
			setTouchLEDRGB(Num3,255,255,0);

			if (getTouchLEDValue(Num1)== 1)
			{
				N1 = N1 +1;
				Touch = Touch +1;
			}
			if (getTouchLEDValue(Num2)== 1)
				N1 = N1 +10;

			if (getTouchLEDValue(Num3)== 1)
				N1 = N1 +10;


			wait1Msec(10);
			Count = Count +1;
		}
		if (N1 < 10)
		{
			N1 = 0;
			Touch = 0;
			Count = 0;
			//
			//Second stone
			//
			while(Count <= 400 || Touch == 0)
			{

				setTouchLEDRGB(Num1,255,255,0);
				setTouchLEDRGB(Num2,255,255,0);
				setTouchLEDRGB(Num3,160,70,0);

				if (getTouchLEDValue(Num1)== 1)
					N1 = N1 +10;
				if (getTouchLEDValue(Num2)== 1)
					N1 = N1 +10;

				if (getTouchLEDValue(Num3)== 1)
				{
					N1 = N1 +1;
					Touch = Touch +1;
				}


				wait1Msec(10);
				Count = Count +1;
			}

			if (N1 < 10)
			{
				N1 = 0;
				Touch = 0;
				Count = 0;
				//
				//Third stone
				//
				while(Count <= 400 || Touch == 0)
				{

					setTouchLEDRGB(Num1,255,255,0);
					setTouchLEDRGB(Num2,160,70,0);
					setTouchLEDRGB(Num3,255,255,0);

					if (getTouchLEDValue(Num1)== 1)
						N1 = N1 +10;
					if (getTouchLEDValue(Num2)== 1)
					{
						N1 = N1 +1;
						Touch = Touch +1;
					}
					if (getTouchLEDValue(Num3)== 1)
						N1 = N1 +10;


					wait1Msec(10);
					Count = Count +1;
				}

				if (N1 < 10)
				{
					N1 = 0;
					Touch = 0;
					Count = 0;
					//
					//Fourth stone
					//
					while(Count <= 400 || Touch == 0)
					{

						setTouchLEDRGB(Num1,255,255,0);
						setTouchLEDRGB(Num2,255,255,0);
						setTouchLEDRGB(Num3,160,70,0);

						if (getTouchLEDValue(Num1)== 1)
							N1 = N1 +10;
						if (getTouchLEDValue(Num2)== 1)
							N1 = N1 +10;
						if (getTouchLEDValue(Num3)== 1)
						{
							N1 = N1 +1;
							Touch = Touch +1;
						}
						wait1Msec(10);
						Count = Count +1;
					}

				}
				setTouchLEDRGB(Num1,0,255,0);
				setTouchLEDRGB(Num2,0,0,255);
				setTouchLEDRGB(Num3,255,0,0);

				Del();
				//
				//You survive acid
				//

				displayTextLine(1,"You made it");
				sleep(100);
				displayTextLine(2,"");
				sleep(1000);
				displayTextLine(3,"You continue");
				sleep(1000);
				displayTextLine(4,"Along the path");
				sleep(1000);
				displayTextLine(5,"");
				sleep(150);

				Del();

				displayTextLine(1,"After a little");
				sleep(1000);
				displayTextLine(2,"Walk you find");
				sleep(1000);
				displayTextLine(3,"The origin of the");
				sleep(1000);
				displayTextLine(4,"Acid, a dying");
				sleep(1000);
				displayTextLine(5,"Mantecore");
				sleep(1500);

				Del();

				displayTextLine(1,"It has two");
				sleep(1000);
				displayTextLine(2,"Massive puncture");
				sleep(1000);
				displayTextLine(3,"Wounds in its");
				sleep(1000);
				displayTextLine(4,"Neck...");
				sleep(1000);
				displayTextLine(5,"");
				sleep(1500);

				Del();

				N1 = 0;
				displayTextLine(1,"Do you?");
				sleep(1000);
				displayTextLine(2,"");
				sleep(1000);
				displayTextLine(3,"Save it?(Green)");
				sleep(1000);
				displayTextLine(4,"Leave it?(Blue)");
				sleep(1000);
				displayTextLine(5,"Kill it(Red)");
				sleep(1500);
				//
				//Save,Kill,Leave Mantecore
				//
				N1 = 0;
				while(N1 == 0)
				{
					setTouchLEDRGB(Num1,0,255,0);
					setTouchLEDRGB(Num2,0,0,255);
					setTouchLEDRGB(Num3,255,0,0);

					if (getTouchLEDValue(Num1)== 1)
					{
						N1 = N1 +1;
					}else if (getTouchLEDValue(Num2)== 1)
					{
						N1 = N1 +2;
					}else if (getTouchLEDValue(Num3)== 1)
					{
						N1 = N1 +3;
					}

				}
				//
				//Save Mantecore
				//
				if (N1 == 1)
				{
					N1 = 0;
					Del();

					displayTextLine(1,"You rip a peice");
					sleep(1000);
					displayTextLine(2,"Of cloth off you");
					sleep(1000);
					displayTextLine(3,"And rap it around");
					sleep(1000);
					displayTextLine(4,"The wound and");
					sleep(1000);
					displayTextLine(5,"Spend the night");
					sleep(1500);

					Del();

					displayTextLine(1,"With it.");
					sleep(1000);
					displayTextLine(2,"");
					sleep(1000);
					displayTextLine(3,"The next morning");
					sleep(1000);
					displayTextLine(4,"You wake up and");
					sleep(1000);
					displayTextLine(5,"find it waiting");
					sleep(1500);

					Del();

					displayTextLine(1,"For you.");
					sleep(1000);
					displayTextLine(2,"It licks you");
					sleep(1000);
					displayTextLine(3,"And flies away.");
					sleep(1000);
					displayTextLine(4,"You shout,");
					sleep(1000);
					displayTextLine(5,"CYA GET WELL");
					sleep(1500);

					Del();

					displayTextLine(1,"AND BE CAREFUL!");
					sleep(1000);
					displayTextLine(2,"The Mantecore");
					sleep(1000);
					displayTextLine(3,"Roars back at you.");
					sleep(1000);
					displayTextLine(4,"");
					sleep(100);
					displayTextLine(5,"");
					sleep(100);

					Manticore = 1;
					N1 = 10;
					Del();
				}
				//
				//Leave Mantecore
				//
				if (N1 == 2)
				{
					N1 = 0;

					Del();

					displayTextLine(1,"You look at the");
					sleep(1000);
					displayTextLine(2,"Manticore and pass");
					sleep(1000);
					displayTextLine(3,"By it not thinking");
					sleep(1000);
					displayTextLine(4,"Twice.");
					sleep(1000);
					displayTextLine(5,"");
					sleep(1500);

					N1 = 10;
					Del();
				}
				//
				//Kill Mantecore with kindness
				//
				if (N1 == 3)
				{
					N1 = 0;

					Del();

					displayTextLine(1,"You charge at it");
					sleep(1000);
					displayTextLine(2,"And swipe.");
					sleep(1000);
					displayTextLine(3,"The Mantecore");
					sleep(1000);
					displayTextLine(4,"Spits acid on");
					sleep(1000);
					displayTextLine(5,"You quickly");
					sleep(1500);

					Del();

					displayTextLine(1,"Decided to jump");
					sleep(1000);
					displayTextLine(2,"Into acid again?");
					sleep(1000);
					displayTextLine(3,"Good Job...");
					sleep(1000);
					displayTextLine(4,"   GAME OVER!");
					sleep(1000);
					displayTextLine(5,"You loose");
					N1 = 0;
					sleep(1500000000);

				}

				if (N1 == 10)
				{
					Del();

					displayTextLine(1,"Good job you");
					sleep(1000);
					displayTextLine(2,"Made it continue");
					sleep(1000);
					displayTextLine(3,"To program called");
					sleep(1000);
					displayTextLine(4,"  THE END");
					sleep(4000);
					displayTextLine(5,"");

					if (Manticore == 1)
					{

						Del();

						displayTextLine(1,"Good choice");
						sleep(1000);
						displayTextLine(2,"Saving the");
						sleep(1000);
						displayTextLine(3,"Manticore");
						sleep(1000);
						displayTextLine(4,"Here you go");
						sleep(1000);
						displayTextLine(5,"Bonus points");
						sleep(3000);

						Del();

						while (Points < 100000)
						{
							displayTextLine(1,"Points: %d", Points);

							Points = Points + 111;


						}

						Del();

						displayTextLine(1,"What are you");
						sleep(1000);
						displayTextLine(2,"Waiting for?");
						sleep(1000);
						displayTextLine(3,"Go to program");
						sleep(1000);
						displayTextLine(4,"    THE END");
						sleep(1000);
						displayTextLine(5,"    GO NOW!");
						sleep(100000000);

					}


				}


			}
			//
			//You jumped into acid
			//
			if (N1 >= 10)
			{
				setTouchLEDRGB(Num1,0,255,0);
				setTouchLEDRGB(Num2,0,0,255);
				setTouchLEDRGB(Num3,255,0,0);

				Del();

				displayTextLine(1,"You jump into Acid ");
				sleep(1000);
				displayTextLine(2,"Great Job you died");
				sleep(1000);
				displayTextLine(3,"Get better reflexes");
				sleep(1000);
				displayTextLine(4,"And jump on rocks");
				sleep(1000);
				displayTextLine(5,"Not into Acid");
				sleep(1500);


			}



		}

	}
}
