#pragma config(Sensor, port6,  Button,         sensorVexIQ_Touch)
#pragma config(Sensor, port7,  Num1,           sensorVexIQ_LED)
#pragma config(Sensor, port8,  Num2,           sensorVexIQ_LED)
#pragma config(Sensor, port9,  Num3,           sensorVexIQ_LED)
#pragma config(Sensor, port11, Distance,       sensorVexIQ_Distance)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void Del () {
	displayTextLine(1," ");
	displayTextLine(2," ");
	displayTextLine(3," ");
	displayTextLine(4," ");
	displayTextLine(5," ");
	sleep(2000);

}
int N1 = 2;
int Goblin = 0;
int Hits;
int Count;
int Final = 0;
int Ogre = 0;
int Gold = 0;
int CL = 0;
int Touched = 0;
int Dist = 0;
task main()
{
	setTouchLEDRGB(Num1,0,255,0);
	setTouchLEDRGB(Num2,0,0,255);
	setTouchLEDRGB(Num3,255,0,0);
	//
	//
	//Second path!!!!!
	//
	//
	if (N1 == 2)  {

		Del();

		displayTextLine(1,"You keep moving");
		sleep(1000);
		displayTextLine(2,"Forward and as");
		sleep(1000);
		displayTextLine(3,"You walk the path ");
		sleep(1000);
		displayTextLine(4,"It seems to be");
		sleep(1000);
		displayTextLine(5,"Getting tighter as");
		sleep(1500);

		Del();

		displayTextLine(1,"You move");
		sleep(1000);
		displayTextLine(2,"");
		sleep(1000);
		displayTextLine(3,"Eventually you find");
		sleep(1000);
		displayTextLine(4,"That there is a");
		sleep(1000);
		displayTextLine(5,"Giant ogre blocking");
		sleep(1500);

		Del();

		displayTextLine(1,"You're path and");
		sleep(1000);
		displayTextLine(2,"You're only choices");
		sleep(1000);
		displayTextLine(3,"Seem to be to Run");
		sleep(1000);
		displayTextLine(4,"Or Fight");
		sleep(1000);
		displayTextLine(5,"");
		sleep(1500);

		Del();

		displayTextLine(1,"What will you do?");
		sleep(1000);
		displayTextLine(2,"");
		sleep(1000);
		displayTextLine(3,"");
		sleep(1000);
		displayTextLine(4,"RUN   (Green)");
		sleep(1000);
		displayTextLine(5,"FIGHT (Red)");
		sleep(1500);
		N1 = 0;
		//
		// Run or fight ogre
		//
		while(N1 == 0)
		{
			setTouchLEDRGB(Num1,0,255,0);
			setTouchLEDRGB(Num2,0,0,255);
			setTouchLEDRGB(Num3,255,0,0);

			if (getTouchLEDValue(Num1)== 1)
				N1 = N1 +1;

			if (getTouchLEDValue(Num3)== 1)
				N1 = N1 +2;

		}
		if (N1 == 1) {
			//
			//RUN AWAY FROM OGRE
			//

			Del();

			displayTextLine(1,"I... I should ");
			sleep(1000);
			displayTextLine(2,"Turn back...");
			sleep(1000);
			displayTextLine(3,"You decide the ");
			sleep(1000);
			displayTextLine(4,"Best option is");
			sleep(1000);
			displayTextLine(5,"To not fight and");
			sleep(1500);

			Del();

			displayTextLine(1,"Go back the way");
			sleep(1000);
			displayTextLine(2,"You came...");
			sleep(1000);
			displayTextLine(3,"But something seems");
			sleep(1000);
			displayTextLine(4,"Different the path");
			sleep(1000);
			displayTextLine(5,"Is winding in ways it");
			sleep(1500);

			Del();

			displayTextLine(1,"Wasn't before...");
			sleep(1000);
			displayTextLine(2,"You head down forks");
			sleep(1000);
			displayTextLine(3,"In the road and lose");
			sleep(1000);
			displayTextLine(4,"Track of time...");
			sleep(1000);
			displayTextLine(5,"");
			sleep(1500);

			Del();

			displayTextLine(1,"     Game Over");
			sleep(1000);
			displayTextLine(2,"");
			sleep(1000);
			displayTextLine(3,"You died of starvation");
			sleep(1000);
			displayTextLine(4,"Good job...");
			sleep(1000);
			displayTextLine(5,"");
			sleep(1500);
			N1 = 0;
		}
		//
		//Fight the Ogre
		//
		if (N1 == 2)
		{
			Del();

			displayTextLine(1,"I'll Fight!!");
			sleep(1000);
			displayTextLine(2,"It seems the only");
			sleep(1000);
			displayTextLine(3,"Way forward is to");
			sleep(1000);
			displayTextLine(4,"Fight!");
			sleep(1000);
			displayTextLine(5,"The ogre is a big");
			sleep(1500);

			Del();

			displayTextLine(1,"And hefty beast it");
			sleep(1000);
			displayTextLine(2,"Can take a lot of");
			sleep(1000);
			displayTextLine(3,"Hits... But hes");
			sleep(1000);
			displayTextLine(4,"Also very slow you");
			sleep(1000);
			displayTextLine(5,"Need to hit it 300");
			sleep(1500);

			Del();

			displayTextLine(1,"Times before he");
			sleep(1000);
			displayTextLine(2,"Swings his weapon.");
			sleep(1000);
			displayTextLine(3,"");
			sleep(1000);
			displayTextLine(4,"");
			sleep(100);
			displayTextLine(5,"");
			sleep(150);

			Del();

			displayTextLine(1,"You have 10 seconds");
			sleep(1000);
			displayTextLine(2,"To hit the Ogre 300");
			sleep(1000);
			displayTextLine(3,"Times ");
			sleep(1000);
			displayTextLine(4,"(Hit the button)");
			sleep(1000);
			displayTextLine(5,"Starting........ ");
			sleep(1500);

			Del();

			displayTextLine(1,"Now!!!");

			displayTextLine(2,"Start hitting ");


			N1 = 0;
			Hits = 0;
			Count = 0;
			//Ogre Combat
			while(Count <= 1000)
			{
				if (getBumperValue(Button)== 1)
				{
					Hits +=1;
				}

				displayTextLine(3,"Hits: %d",Hits);

				Count +=1;
				wait1Msec(10);
			}

			Del();

			if (Hits >= 300)
			{
				//
				//You kill ogre good job
				//
				Ogre = 1;
			}
			if (Ogre == 1)
			{
				Del();

				displayTextLine(1,"You defeat the ogre");
				sleep(1000);
				displayTextLine(2,"And continue on the");
				sleep(1000);
				displayTextLine(3,"Path");
				sleep(1000);
				displayTextLine(4,"On your way through");
				sleep(1000);
				displayTextLine(5,"A small strange ");
				sleep(2000);

				Del();

				displayTextLine(1,"Little creature");
				sleep(1000);
				displayTextLine(2,"That looked a bit");
				sleep(1000);
				displayTextLine(3,"Like a human");
				sleep(1000);
				displayTextLine(4,"It asks for gold");
				sleep(1000);
				displayTextLine(5,"");
				sleep(2000);

				Del();

				displayTextLine(1,"What will you do?");
				sleep(1000);
				displayTextLine(2,"");
				sleep(1000);
				displayTextLine(3,"Give it Gold(Green)");
				sleep(1000);
				displayTextLine(4,"Fight it    (Blue)");
				sleep(1000);
				displayTextLine(5,"Scare it away(Red)");
				sleep(2000);

				//
				//Fight, give gold or scare away Goblin
				//
				N1 = 0;

				while(N1 == 0)
				{
					setTouchLEDRGB(Num1,0,255,0);
					setTouchLEDRGB(Num2,0,0,255);
					setTouchLEDRGB(Num3,255,0,0);

					if (getTouchLEDValue(Num1)== 1) {
						N1 = N1 +1;
					}
					if (getTouchLEDValue(Num2)== 1) {
						N1 = N1 +2;
					}
					if (getTouchLEDValue(Num3)== 1) {
						N1 = N1 +3;
					}
				}
				//
				//Give gold to goblin thing
				//
				if (N1 == 1)
				{

					Del();

					displayTextLine(1,"Luckily the Emperor");
					sleep(1000);
					displayTextLine(2,"Gave you some gold");
					sleep(1000);
					displayTextLine(3,"Give it to the");
					sleep(1000);
					displayTextLine(4,"Creature");
					sleep(1000);
					displayTextLine(5,"Hold hand 5cm");
					sleep(2000);

					Del();

					displayTextLine(1,"Above the sensor");
					sleep(1000);
					displayTextLine(2,"");
					sleep(1000);


					CL = 0;
					Gold = 1;
					Dist = 0;
					while(Touched == 0)
					{
						if (getDistanceValue(Distance) < 60 )
						{
							if (getDistanceValue(Distance) > 40)
							Touched = Touched +1;
						}
						Dist = getDistanceValue(Distance)/10;
						setTouchLEDRGB(Num1,0,255,0);
						setTouchLEDRGB(Num2,0,0,255);
						setTouchLEDRGB(Num3,255,0,0);
						displayTextLine(3,"Dist: %d",Dist);


					}

					N1 = 2;
				}
				//
				//Fight Goblin thing
				//
				if (N1 == 2)
				{
					Del();
					if (Gold == 1)
					{
						displayTextLine(1,"The creature wants");
						sleep(1000);
						displayTextLine(2,"More gold but you don't");
						sleep(1000);
						displayTextLine(3,"Have more it fights you");
						sleep(1000);
					}
					displayTextLine(4,"Hit it 150 times");
					sleep(1000);
					displayTextLine(5,"In 5 seconds");
					sleep(2000);

					Del();


					displayTextLine(1,"Start hitting");
					sleep(1000);
					displayTextLine(2,"Now!");
					sleep(0);
					displayTextLine(3,"");
					sleep(0);
					displayTextLine(4,"");
					sleep(0);
					displayTextLine(5,"");
					sleep(0);

					Hits = 0;
					Count = 0;
					Ogre = 1;
					//
					//Goblin Combat
					//
					while(Count <= 500)
					{
						if (getBumperValue(Button)== 1)
						{
							Hits +=1;
						}
						displayTextLine(3,"Hits: %d", Hits);
						Count +=1;
						wait1Msec(10);
					}
        if (Hits >= 150)
        {
					Goblin = 1;
					N1 = 0;
					Final = 1;
				}else
				{
					Del();


					displayTextLine(1,"Good Job");
					sleep(1000);
					displayTextLine(2,"You died");
					sleep(1000);
					displayTextLine(3,"Whoooo");
					sleep(1000);
					displayTextLine(4,"Nice... IDK");
					sleep(1000);
					displayTextLine(5,"");
					sleep(10000000000000000);


			}
				}
				//
				//Scare away Goblin thing
				//
				if (N1 == 3)
				{
					Del();

					displayTextLine(1,"You walk back to");
					sleep(1000);
					displayTextLine(2,"The ogres carcass");
					sleep(1000);
					displayTextLine(3,"Grab the head and");
					sleep(1000);
					displayTextLine(4,"Return.");
					sleep(1000);
					displayTextLine(5,"");
					sleep(2000);

					Del();

					displayTextLine(1,"The creature is");
					sleep(1000);
					displayTextLine(2,"Terryfied and");
					sleep(1000);
					displayTextLine(3,"Runs away");
					sleep(1000);
					displayTextLine(4,"");
					sleep(1000);
					displayTextLine(5,"");
					sleep(2000);

					Del();

					displayTextLine(1,"Now go to");
					sleep(1000);
					displayTextLine(2,"Program called");
					sleep(1000);
					displayTextLine(3,"Final Trial");
					sleep(1000);
					displayTextLine(4,"To finish");
					sleep(1000);
					displayTextLine(5,"Game");
					sleep(2000);
					N1 = 0;
					Final = 1;
				}
			} if (Ogre == 0)
			{
				//
				//Your too slow and die to ogre
				//

				Del();

				displayTextLine(1,"The ogre winds up");
				sleep(1000);
				displayTextLine(2,"For a swing and");
				sleep(1000);
				displayTextLine(3,"Gets your head");
				sleep(1000);
				displayTextLine(4,"Which rips off");
				sleep(1000);
				displayTextLine(5,"And flies away");
				sleep(2000);

				Del();

				N1 = 0;

				displayTextLine(1,"Good job You died");
				sleep(1000);
				displayTextLine(2,"    GAME OVER! ");
				sleep(1000);
				displayTextLine(3,"Go play cookie");
				sleep(1000);
				displayTextLine(4,"clicker and try");
				sleep(1000);
				displayTextLine(5,"     Again!");
				sleep(1500);


			}


		}
	}




Del();

 if (Final == 1)
 {
	displayTextLine(1,"Great now move");
	sleep(1000);
	displayTextLine(2,"To program");
	sleep(1000);
	displayTextLine(3,"Final to finish");
	sleep(1000);
	displayTextLine(4,"The game");
	sleep(1000);
	displayTextLine(5,"Cya there!!");
	sleep(1500);
	sleep(2000000);
}
}
