#pragma config(Sensor, port6,  Button,         sensorVexIQ_Touch)
#pragma config(Sensor, port7,  Num1,           sensorVexIQ_LED)
#pragma config(Sensor, port8,  Num2,           sensorVexIQ_LED)
#pragma config(Sensor, port9,  Num3,           sensorVexIQ_LED)
#pragma config(Sensor, port11, Distance,       sensorVexIQ_Distance)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
int Left2 = 40;
int Top2 = 40;

void F2 (int Left2, int Top2)
{
	//is 29 tall
  //25 wide idk

//First row
setPixel(Left2 +9,Top2);
setPixel(Left2 +10,Top2);
setPixel(Left2 +11,Top2);
setPixel(Left2 +12,Top2);
setPixel(Left2 +13,Top2);

//Second Row
setPixel(Left2 +8,Top2 -1);
setPixel(Left2 +11,Top2 -1);
setPixel(Left2 +12,Top2 -1);
setPixel(Left2 +13,Top2 -1);

//Third Row
setPixel(Left2 +5,Top2 -2);
setPixel(Left2 +7,Top2 -2);
setPixel(Left2 +8,Top2 -2);
setPixel(Left2 +9,Top2 -2);
setPixel(Left2 +10,Top2 -2);
setPixel(Left2 +14,Top2 -2);
setPixel(Left2 +15,Top2 -2);
setPixel(Left2 +16,Top2 -2);

//Fourth Row
setPixel(Left2 +4,Top2 -3);
setPixel(Left2 +5,Top2 -3);
setPixel(Left2 +7,Top2 -3);
setPixel(Left2 +8,Top2 -3);
setPixel(Left2 +9,Top2 -3);
setPixel(Left2 +11,Top2 -3);
setPixel(Left2 +12,Top2 -3);
setPixel(Left2 +13,Top2 -3);
setPixel(Left2 +14,Top2 -3);
setPixel(Left2 +15,Top2 -3);
setPixel(Left2 +16,Top2 -3);

//Fifth Row
setPixel(Left2 +4,Top2 -4);
setPixel(Left2 +5,Top2 -4);
setPixel(Left2 +8,Top2 -4);
setPixel(Left2 +10,Top2 -4);
setPixel(Left2 +11,Top2 -4);
setPixel(Left2 +13,Top2 -4);
setPixel(Left2 +14,Top2 -4);
setPixel(Left2 +15,Top2 -4);
setPixel(Left2 +16,Top2 -4);

//Sixth Row
setPixel(Left2 +4,Top2 -5);
setPixel(Left2 +5,Top2 -5);
setPixel(Left2 +7,Top2 -5);
setPixel(Left2 +9,Top2 -5);
setPixel(Left2 +12,Top2 -5);
setPixel(Left2 +13,Top2 -5);
setPixel(Left2 +14,Top2 -5);

//Seventh Row
setPixel(Left2 +4,Top2 -6);
setPixel(Left2 +5,Top2 -6);
setPixel(Left2 +7,Top2 -6);
setPixel(Left2 +8,Top2 -6);
setPixel(Left2 +15,Top2 -6);
setPixel(Left2 +16,Top2 -6);
setPixel(Left2 +17,Top2 -6);

//Eigth Row
setPixel(Left2 +1,Top2 -7);
setPixel(Left2 +2,Top2 -7);
setPixel(Left2 +3,Top2 -7);
setPixel(Left2 +5,Top2 -7);
setPixel(Left2 +7,Top2 -7);
setPixel(Left2 +8,Top2 -7);
setPixel(Left2 +9,Top2 -7);
setPixel(Left2 +10,Top2 -7);
setPixel(Left2 +11,Top2 -7);
setPixel(Left2 +12,Top2 -7);
setPixel(Left2 +14,Top2 -7);
setPixel(Left2 +15,Top2 -7);
setPixel(Left2 +16,Top2 -7);
setPixel(Left2 +17,Top2 -7);
setPixel(Left2 +18,Top2 -7);

//Ninth Row
setPixel(Left2 +2,Top2 -8);
setPixel(Left2 +3,Top2 -8);
setPixel(Left2 +4,Top2 -8);
setPixel(Left2 +6,Top2 -8);
setPixel(Left2 +8,Top2 -8);
setPixel(Left2 +9,Top2 -8);
setPixel(Left2 +10,Top2 -8);
setPixel(Left2 +11,Top2 -8);
setPixel(Left2 +13,Top2 -8);
setPixel(Left2 +14,Top2 -8);
setPixel(Left2 +15,Top2 -8);
setPixel(Left2 +16,Top2 -8);
setPixel(Left2 +17,Top2 -8);
setPixel(Left2 +18,Top2 -8);

//Tenth Row
setPixel(Left2 +2,Top2 -9);
setPixel(Left2 +3,Top2 -9);
setPixel(Left2 +4,Top2 -9);
setPixel(Left2 +5,Top2 -9);
setPixel(Left2 +7,Top2 -9);
setPixel(Left2 +15,Top2 -9);
setPixel(Left2 +16,Top2 -9);
setPixel(Left2 +17,Top2 -9);

//Eleventh Row
setPixel(Left2 +3,Top2 -10);
setPixel(Left2 +4,Top2 -10);
setPixel(Left2 +5,Top2 -10);
setPixel(Left2 +6,Top2 -10);
setPixel(Left2 +8,Top2 -10);
setPixel(Left2 +9,Top2 -10);
setPixel(Left2 +10,Top2 -10);
setPixel(Left2 +11,Top2 -10);
setPixel(Left2 +12,Top2 -10);
setPixel(Left2 +13,Top2 -10);
setPixel(Left2 +14,Top2 -10);
setPixel(Left2 +16,Top2 -10);

//Twelth Row
setPixel(Left2 +4,Top2 -11);
setPixel(Left2 +5,Top2 -11);
setPixel(Left2 +6,Top2 -11);
setPixel(Left2 +7,Top2 -11);
setPixel(Left2 +9,Top2 -11);
setPixel(Left2 +10,Top2 -11);
setPixel(Left2 +11,Top2 -11);
setPixel(Left2 +12,Top2 -11);
setPixel(Left2 +13,Top2 -11);
setPixel(Left2 +14,Top2 -11);
setPixel(Left2 +15,Top2 -11);

//Thirteenth Row
setPixel(Left2 +12,Top2 -12);
setPixel(Left2 +13,Top2 -12);
setPixel(Left2 +14,Top2 -12);
setPixel(Left2 +15,Top2 -12);

//Fourteenth Row
setPixel(Left2 +4,Top2 -13);
setPixel(Left2 +5,Top2 -13);
setPixel(Left2 +6,Top2 -13);
setPixel(Left2 +7,Top2 -13);
setPixel(Left2 +8,Top2 -13);
setPixel(Left2 +10,Top2 -13);
setPixel(Left2 +11,Top2 -13);
setPixel(Left2 +14,Top2 -13);

//Fifteenth Row
setPixel(Left2 +3,Top2 -14);
setPixel(Left2 +4,Top2 -14);
setPixel(Left2 +5,Top2 -14);
setPixel(Left2 +6,Top2 -14);
setPixel(Left2 +7,Top2 -14);
setPixel(Left2 +9,Top2 -14);
setPixel(Left2 +10,Top2 -14);
setPixel(Left2 +11,Top2 -14);
setPixel(Left2 +12,Top2 -14);

//Sixteenth Row
setPixel(Left2 +3,Top2 -15);
setPixel(Left2 +4,Top2 -15);
setPixel(Left2 +5,Top2 -15);
setPixel(Left2 +6,Top2 -15);
setPixel(Left2 +7,Top2 -15);
setPixel(Left2 +9,Top2 -15);
setPixel(Left2 +10,Top2 -15);
setPixel(Left2 +11,Top2 -15);
setPixel(Left2 +12,Top2 -15);
setPixel(Left2 +13,Top2 -15);

//Seventeenth Row
setPixel(Left2 +3,Top2 -16);
setPixel(Left2 +4,Top2 -16);
setPixel(Left2 +5,Top2 -16);
setPixel(Left2 +6,Top2 -16);
setPixel(Left2 +9,Top2 -16);
setPixel(Left2 +10,Top2 -16);
setPixel(Left2 +11,Top2 -16);
setPixel(Left2 +12,Top2 -16);
setPixel(Left2 +13,Top2 -16);
setPixel(Left2 +14,Top2 -16);

//Eigteenth Row
setPixel(Left2 +3,Top2 -17);
setPixel(Left2 +4,Top2 -17);
setPixel(Left2 +9,Top2 -17);
setPixel(Left2 +11,Top2 -17);
setPixel(Left2 +12,Top2 -17);
setPixel(Left2 +13,Top2 -17);
setPixel(Left2 +14,Top2 -17);
setPixel(Left2 +15,Top2 -17);
setPixel(Left2 +19,Top2 -17);
setPixel(Left2 +20,Top2 -17);
setPixel(Left2 +21,Top2 -17);

//Ninteenth Row
setPixel(Left2 +9,Top2 -18);
setPixel(Left2 +17,Top2 -18);
setPixel(Left2 +19,Top2 -18);
setPixel(Left2 +20,Top2 -18);
setPixel(Left2 +21,Top2 -18);

//Twenteeth Row
setPixel(Left2 +8,Top2 -19);
setPixel(Left2 +9,Top2 -19);
setPixel(Left2 +14,Top2 -19);
setPixel(Left2 +16,Top2 -19);
setPixel(Left2 +17,Top2 -19);
setPixel(Left2 +19,Top2 -19);
setPixel(Left2 +20,Top2 -19);
setPixel(Left2 +22,Top2 -19);
setPixel(Left2 +23,Top2 -19);

//TwenteeFirst Row
setPixel(Left2 +8,Top2 -20);
setPixel(Left2 +9,Top2 -20);
setPixel(Left2 +13,Top2 -20);
setPixel(Left2 +14,Top2 -20);
setPixel(Left2 +15,Top2 -20);
setPixel(Left2 +17,Top2 -20);
setPixel(Left2 +18,Top2 -20);
setPixel(Left2 +20,Top2 -20);
setPixel(Left2 +21,Top2 -20);
setPixel(Left2 +22,Top2 -20);
setPixel(Left2 +23,Top2 -20);

//22 Row
setPixel(Left2 +8,Top2 -21);
setPixel(Left2 +13,Top2 -21);
setPixel(Left2 +14,Top2 -21);
setPixel(Left2 +15,Top2 -21);
setPixel(Left2 +17,Top2 -21);
setPixel(Left2 +20,Top2 -21);
setPixel(Left2 +21,Top2 -21);
setPixel(Left2 +23,Top2 -21);

//23 Row
setPixel(Left2 +7,Top2 -22);
setPixel(Left2 +8,Top2 -22);
setPixel(Left2 +10,Top2 -22);
setPixel(Left2 +11,Top2 -22);
setPixel(Left2 +12,Top2 -22);
setPixel(Left2 +14,Top2 -22);
setPixel(Left2 +15,Top2 -22);
setPixel(Left2 +17,Top2 -22);
setPixel(Left2 +19,Top2 -22);
setPixel(Left2 +22,Top2 -22);
setPixel(Left2 +24,Top2 -22);

//24 Row
setPixel(Left2 +7,Top2 -23);
setPixel(Left2 +8,Top2 -23);
setPixel(Left2 +9,Top2 -23);
setPixel(Left2 +12,Top2 -23);
setPixel(Left2 +13,Top2 -23);
setPixel(Left2 +14,Top2 -23);
setPixel(Left2 +15,Top2 -23);
setPixel(Left2 +17,Top2 -23);
setPixel(Left2 +19,Top2 -23);
setPixel(Left2 +20,Top2 -23);
setPixel(Left2 +22,Top2 -23);
setPixel(Left2 +23,Top2 -23);
setPixel(Left2 +24,Top2 -23);

//25 Row
setPixel(Left2 +6,Top2 -24);
setPixel(Left2 +7,Top2 -24);
setPixel(Left2 +15,Top2 -24);
setPixel(Left2 +17,Top2 -24);
setPixel(Left2 +19,Top2 -24);
setPixel(Left2 +20,Top2 -24);
setPixel(Left2 +21,Top2 -24);
setPixel(Left2 +23,Top2 -24);

//26 Row
setPixel(Left2 +5,Top2 -25);
setPixel(Left2 +6,Top2 -25);
setPixel(Left2 +13,Top2 -25);
setPixel(Left2 +14,Top2 -25);
setPixel(Left2 +15,Top2 -25);
setPixel(Left2 +16,Top2 -25);
setPixel(Left2 +18,Top2 -25);
setPixel(Left2 +23,Top2 -25);

//27 Row
setPixel(Left2 +3,Top2 -26);
setPixel(Left2 +4,Top2 -26);
setPixel(Left2 +5,Top2 -26);
setPixel(Left2 +12,Top2 -26);
setPixel(Left2 +13,Top2 -26);
setPixel(Left2 +14,Top2 -26);
setPixel(Left2 +15,Top2 -26);
setPixel(Left2 +16,Top2 -26);
setPixel(Left2 +17,Top2 -26);
setPixel(Left2 +19,Top2 -26);
setPixel(Left2 +20,Top2 -26);
setPixel(Left2 +21,Top2 -26);
setPixel(Left2 +22,Top2 -26);

//28 Row
setPixel(Left2 +2,Top2 -27);
setPixel(Left2 +3,Top2 -27);
setPixel(Left2 +4,Top2 -27);
setPixel(Left2 +11,Top2 -27);
setPixel(Left2 +12,Top2 -27);
setPixel(Left2 +13,Top2 -27);
setPixel(Left2 +14,Top2 -27);
setPixel(Left2 +17,Top2 -27);
setPixel(Left2 +18,Top2 -27);
setPixel(Left2 +21,Top2 -27);
setPixel(Left2 +22,Top2 -27);

//29 Row
setPixel(Left2,Top2 -28);
setPixel(Left2 +1,Top2 -28);
setPixel(Left2 +2,Top2 -28);
setPixel(Left2 +3,Top2 -28);
setPixel(Left2 +18,Top2 -28);

//Yeah finaly done!!!!!

}
void Del () {
	displayTextLine (1," ");
	displayTextLine(2," ");
	displayTextLine(3," ");
	displayTextLine(4," ");
	displayTextLine(5," ");
	sleep(2000);

}

void Text (string a, string b, string c, string d, string e) {

		displayTextLine(1,a);
			sleep(1000);
			displayTextLine(2,b);
			sleep(1000);
			displayTextLine(3,c);
			sleep(1000);
			displayTextLine(4,d);
			sleep(1000);
			displayTextLine(5,e);
			sleep(1500);
}

int N1 = 0;
task main()
{
setDistanceMaxRange(Distance, 300);

	displayTextLine(1,"Would you like to");
	sleep(1000);
	displayTextLine(2,"Start the game??");
	displayTextLine(3,"");
	sleep(1000);
	displayTextLine(4,"Click the green button");
	displayTextLine(5,"");
	N1 = 0;
	while(getTouchLEDValue(Num1)== 0)
	{
		setTouchLEDRGB(Num1,0,255,0);
		setTouchLEDRGB(Num2,0,0,255);
		setTouchLEDRGB(Num3,255,0,0);

	}
	wait1Msec(1000);
	N1 = 0;



	//Labyrinth Game
	//If you decide not to go in you win!


	Del();

	displayTextLine(1,"The Beloved Emporor");
	sleep(1000);
	displayTextLine(2,"has fallen ill");
	sleep(1000);
	displayTextLine(3,"and requires you");
	sleep(1000);
	displayTextLine(4,"to obtain the");
	sleep(1000);
	displayTextLine(5,"crystal flower from");
	sleep(1500);

	Del();

	displayTextLine(1,", The labyrinth");
	sleep(1000);
	displayTextLine(2," Do you accept???");
	sleep(100);
	displayTextLine(3,"");
	sleep(100);
	displayTextLine(4,"");
	sleep(100);
	displayTextLine(5,"");
	sleep(100);

	Del();

	displayTextLine(1,"Do you accept???");
	sleep(100);
	displayTextLine(2,"");
	sleep(100);
	displayTextLine(3,"");
	sleep(100);
	displayTextLine(4,"Yes  (Green).");
	sleep(1000);
	displayTextLine(5,"No thanks (Red).");
	sleep(1500);

	N1 = 0;

	Del();
	while(N1 == 0)
	{
		F2(Left2, Top2);
		setTouchLEDRGB(Num1,0,255,0);
		setTouchLEDRGB(Num3,255,0,0);


		if (getTouchLEDValue(Num1)== 1)

		N1 = N1 +1;




		if (getTouchLEDValue(Num3)== 1)
		{
			Del();

			displayTextLine(1,"You politely decline");
			sleep(1000);
			displayTextLine(2,"In the end you survive");
			sleep(1000);
			displayTextLine(3,"As a consequence");
			sleep(1000);
			displayTextLine(4,"Of your actions the");
			sleep(1000);
			displayTextLine(5,"Emperor dies and");
			sleep(1500);

			Del();

			displayTextLine(1,"The kingdom falls");
			sleep(1000);
			displayTextLine(2,"Into chaos");
			sleep(1000);
			displayTextLine(3,"");
			sleep(1000);
			displayTextLine(4,"");
			sleep(1000);
			displayTextLine(5,"");
			sleep(100);

			Del();


			displayTextLine(1,"     Game Over!");
			sleep(1000);
			displayTextLine(2,"");
			sleep(1000);
			displayTextLine(3,"     You Survived!");
			sleep(1000);
			displayTextLine(4,"Have a lollipop");
			sleep(1000);
			displayTextLine(5,"");
			sleep(1500);
		}
	}
	if (N1 == 1)
	{
		Del();

		displayTextLine(1,"As you head to the");
		sleep(1000);
		displayTextLine(2,"Labyrinth you notice");
		sleep(1000);
		displayTextLine(3,"That the further");
		sleep(1000);
		displayTextLine(4,"You go the more");
		sleep(1000);
		displayTextLine(5,"Dying and rotting ");
		sleep(1500);

		Del();
	}
	displayTextLine(1,"Trees there are, and");
	sleep(1000);
	displayTextLine(2,"The sky blackens...");
	sleep(1000);
	displayTextLine(3,"");
	sleep(1000);
	displayTextLine(4,"You enter the");
	sleep(1000);
	displayTextLine(5,"Labyrinth and head ");
	sleep(1500);

	Del();


	displayTextLine(1,"Straight you arrive");
	sleep(1000);
	displayTextLine(2,"At a fork in the ");
	sleep(1000);
	displayTextLine(3,"Road and three ");
	sleep(1000);
	displayTextLine(4,"Paths open before you");
	sleep(1000);
	displayTextLine(5,"On the first path");
	sleep(1500);

	Del();

	displayTextLine(1,"You can see wild ");
	sleep(1000);
	displayTextLine(2,"Flowers Growing ");
	sleep(1000);
	displayTextLine(3,"Near the entrance ");
	sleep(1000);
	displayTextLine(4,"And you think you ");
	sleep(1000);
	displayTextLine(5,"See a blueberry patch");
	sleep(1500);

	Del();


	displayTextLine(1,"In the distance");
	sleep(100);
	displayTextLine(2,"");
	sleep(100);
	displayTextLine(3,"");
	sleep(100);
	displayTextLine(4,"");
	sleep(100);
	displayTextLine(5,"");
	sleep(150);

	Del();
	//Second path choice
	displayTextLine(1,"At the entrance of");
	sleep(1000);
	displayTextLine(2,"The second path you");
	sleep(1000);
	displayTextLine(3,"See a discarded ");
	sleep(1000);
	displayTextLine(4,"Rusty longsword on");
	sleep(1000);
	displayTextLine(5,"The ground ");
	sleep(1500);

	Del();
	//Thrid choice path
	displayTextLine(1,"On the third and final");
	sleep(1000);
	displayTextLine(2,"Path you can smell a");
	sleep(1000);
	displayTextLine(3,"Strange scent, like");
	sleep(1000);
	displayTextLine(4,"Rotten meat or,");
	sleep(1000);
	displayTextLine(5,"Something else");
	sleep(1500);

	Del();

	displayTextLine(1,"Which path shall you");
	sleep(1000);
	displayTextLine(2,"Choose");
	sleep(1000);
	displayTextLine(3,"Path one  (Green)");
	sleep(1000);
	displayTextLine(4,"Path two  (Blue)");
	sleep(1000);
	displayTextLine(5,"Path three(Red)");
	sleep(1500);

	N1 = 0;
	//
	//
	// PAth ont two or three
	//
	//
	while(N1 == 0)
	{
		setTouchLEDRGB(Num1,0,255,0);
		setTouchLEDRGB(Num2,0,0,255);
		setTouchLEDRGB(Num3,255,0,0);

		if (getTouchLEDValue(Num1)== 1) {
			N1 = N1 +1;
		}
		if (getTouchLEDValue(Num2)== 1) {
			N1 = N1 +2;
		}
		if (getTouchLEDValue(Num3)== 1) {
			N1 = N1 +3;
		}
	}
	if (N1 == 1)
	{
			Del();

	displayTextLine(1,"Program too big");
	sleep(1000);
	displayTextLine(2,"Error has ocurred");
	sleep(1000);
	displayTextLine(3,"Continue on program");
	sleep(1000);
	displayTextLine(4,"Path 1");
	sleep(1000);
	displayTextLine(5,"");
	sleep(1500000000000000);

}
else if (N1 == 1)
	{
		Del();

	displayTextLine(1,"Program too big");
	sleep(1000);
	displayTextLine(2,"Error has ocurred");
	sleep(1000);
	displayTextLine(3,"Continue on program");
	sleep(1000);
	displayTextLine(4,"Path 2");
	sleep(1000);
	displayTextLine(5,"");
	sleep(1500000000000000);

}
else if (N1 == 1)
	{
		Del();

	displayTextLine(1,"Program too big");
	sleep(1000);
	displayTextLine(2,"Error has ocurred");
	sleep(1000);
	displayTextLine(3,"Continue on program");
	sleep(1000);
	displayTextLine(4,"Path 3");
	sleep(1000);
	displayTextLine(5,"");
	sleep(1500000000000000);

}


}
