#pragma config(Sensor, port6,  Button,         sensorVexIQ_Touch)
#pragma config(Sensor, port7,  Num1,           sensorVexIQ_LED)
#pragma config(Sensor, port8,  Num2,           sensorVexIQ_LED)
#pragma config(Sensor, port9,  Num3,           sensorVexIQ_LED)
#pragma config(Sensor, port11, Distance,       sensorVexIQ_Distance)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
int Left2 = 40;
int Top2 = 40;

void F2 (int Left2, int Top2)
{
	//is 29 tall
	//25 wide idk

	//First row
	setPixel(Left2 +9,Top2);
	setPixel(Left2 +10,Top2);
	setPixel(Left2 +11,Top2);
	setPixel(Left2 +12,Top2);
	setPixel(Left2 +13,Top2);

	//Second Row
	setPixel(Left2 +8,Top2 -1);
	setPixel(Left2 +11,Top2 -1);
	setPixel(Left2 +12,Top2 -1);
	setPixel(Left2 +13,Top2 -1);

	//Third Row
	setPixel(Left2 +5,Top2 -2);
	setPixel(Left2 +7,Top2 -2);
	setPixel(Left2 +8,Top2 -2);
	setPixel(Left2 +9,Top2 -2);
	setPixel(Left2 +10,Top2 -2);
	setPixel(Left2 +14,Top2 -2);
	setPixel(Left2 +15,Top2 -2);
	setPixel(Left2 +16,Top2 -2);

	//Fourth Row
	setPixel(Left2 +4,Top2 -3);
	setPixel(Left2 +5,Top2 -3);
	setPixel(Left2 +7,Top2 -3);
	setPixel(Left2 +8,Top2 -3);
	setPixel(Left2 +9,Top2 -3);
	setPixel(Left2 +11,Top2 -3);
	setPixel(Left2 +12,Top2 -3);
	setPixel(Left2 +13,Top2 -3);
	setPixel(Left2 +14,Top2 -3);
	setPixel(Left2 +15,Top2 -3);
	setPixel(Left2 +16,Top2 -3);

	//Fifth Row
	setPixel(Left2 +4,Top2 -4);
	setPixel(Left2 +5,Top2 -4);
	setPixel(Left2 +8,Top2 -4);
	setPixel(Left2 +10,Top2 -4);
	setPixel(Left2 +11,Top2 -4);
	setPixel(Left2 +13,Top2 -4);
	setPixel(Left2 +14,Top2 -4);
	setPixel(Left2 +15,Top2 -4);
	setPixel(Left2 +16,Top2 -4);

	//Sixth Row
	setPixel(Left2 +4,Top2 -5);
	setPixel(Left2 +5,Top2 -5);
	setPixel(Left2 +7,Top2 -5);
	setPixel(Left2 +9,Top2 -5);
	setPixel(Left2 +12,Top2 -5);
	setPixel(Left2 +13,Top2 -5);
	setPixel(Left2 +14,Top2 -5);

	//Seventh Row
	setPixel(Left2 +4,Top2 -6);
	setPixel(Left2 +5,Top2 -6);
	setPixel(Left2 +7,Top2 -6);
	setPixel(Left2 +8,Top2 -6);
	setPixel(Left2 +15,Top2 -6);
	setPixel(Left2 +16,Top2 -6);
	setPixel(Left2 +17,Top2 -6);

	//Eigth Row
	setPixel(Left2 +1,Top2 -7);
	setPixel(Left2 +2,Top2 -7);
	setPixel(Left2 +3,Top2 -7);
	setPixel(Left2 +5,Top2 -7);
	setPixel(Left2 +7,Top2 -7);
	setPixel(Left2 +8,Top2 -7);
	setPixel(Left2 +9,Top2 -7);
	setPixel(Left2 +10,Top2 -7);
	setPixel(Left2 +11,Top2 -7);
	setPixel(Left2 +12,Top2 -7);
	setPixel(Left2 +14,Top2 -7);
	setPixel(Left2 +15,Top2 -7);
	setPixel(Left2 +16,Top2 -7);
	setPixel(Left2 +17,Top2 -7);
	setPixel(Left2 +18,Top2 -7);

	//Ninth Row
	setPixel(Left2 +2,Top2 -8);
	setPixel(Left2 +3,Top2 -8);
	setPixel(Left2 +4,Top2 -8);
	setPixel(Left2 +6,Top2 -8);
	setPixel(Left2 +8,Top2 -8);
	setPixel(Left2 +9,Top2 -8);
	setPixel(Left2 +10,Top2 -8);
	setPixel(Left2 +11,Top2 -8);
	setPixel(Left2 +13,Top2 -8);
	setPixel(Left2 +14,Top2 -8);
	setPixel(Left2 +15,Top2 -8);
	setPixel(Left2 +16,Top2 -8);
	setPixel(Left2 +17,Top2 -8);
	setPixel(Left2 +18,Top2 -8);

	//Tenth Row
	setPixel(Left2 +2,Top2 -9);
	setPixel(Left2 +3,Top2 -9);
	setPixel(Left2 +4,Top2 -9);
	setPixel(Left2 +5,Top2 -9);
	setPixel(Left2 +7,Top2 -9);
	setPixel(Left2 +15,Top2 -9);
	setPixel(Left2 +16,Top2 -9);
	setPixel(Left2 +17,Top2 -9);

	//Eleventh Row
	setPixel(Left2 +3,Top2 -10);
	setPixel(Left2 +4,Top2 -10);
	setPixel(Left2 +5,Top2 -10);
	setPixel(Left2 +6,Top2 -10);
	setPixel(Left2 +8,Top2 -10);
	setPixel(Left2 +9,Top2 -10);
	setPixel(Left2 +10,Top2 -10);
	setPixel(Left2 +11,Top2 -10);
	setPixel(Left2 +12,Top2 -10);
	setPixel(Left2 +13,Top2 -10);
	setPixel(Left2 +14,Top2 -10);
	setPixel(Left2 +16,Top2 -10);

	//Twelth Row
	setPixel(Left2 +4,Top2 -11);
	setPixel(Left2 +5,Top2 -11);
	setPixel(Left2 +6,Top2 -11);
	setPixel(Left2 +7,Top2 -11);
	setPixel(Left2 +9,Top2 -11);
	setPixel(Left2 +10,Top2 -11);
	setPixel(Left2 +11,Top2 -11);
	setPixel(Left2 +12,Top2 -11);
	setPixel(Left2 +13,Top2 -11);
	setPixel(Left2 +14,Top2 -11);
	setPixel(Left2 +15,Top2 -11);

	//Thirteenth Row
	setPixel(Left2 +12,Top2 -12);
	setPixel(Left2 +13,Top2 -12);
	setPixel(Left2 +14,Top2 -12);
	setPixel(Left2 +15,Top2 -12);

	//Fourteenth Row
	setPixel(Left2 +4,Top2 -13);
	setPixel(Left2 +5,Top2 -13);
	setPixel(Left2 +6,Top2 -13);
	setPixel(Left2 +7,Top2 -13);
	setPixel(Left2 +8,Top2 -13);
	setPixel(Left2 +10,Top2 -13);
	setPixel(Left2 +11,Top2 -13);
	setPixel(Left2 +14,Top2 -13);

	//Fifteenth Row
	setPixel(Left2 +3,Top2 -14);
	setPixel(Left2 +4,Top2 -14);
	setPixel(Left2 +5,Top2 -14);
	setPixel(Left2 +6,Top2 -14);
	setPixel(Left2 +7,Top2 -14);
	setPixel(Left2 +9,Top2 -14);
	setPixel(Left2 +10,Top2 -14);
	setPixel(Left2 +11,Top2 -14);
	setPixel(Left2 +12,Top2 -14);

	//Sixteenth Row
	setPixel(Left2 +3,Top2 -15);
	setPixel(Left2 +4,Top2 -15);
	setPixel(Left2 +5,Top2 -15);
	setPixel(Left2 +6,Top2 -15);
	setPixel(Left2 +7,Top2 -15);
	setPixel(Left2 +9,Top2 -15);
	setPixel(Left2 +10,Top2 -15);
	setPixel(Left2 +11,Top2 -15);
	setPixel(Left2 +12,Top2 -15);
	setPixel(Left2 +13,Top2 -15);

	//Seventeenth Row
	setPixel(Left2 +3,Top2 -16);
	setPixel(Left2 +4,Top2 -16);
	setPixel(Left2 +5,Top2 -16);
	setPixel(Left2 +6,Top2 -16);
	setPixel(Left2 +9,Top2 -16);
	setPixel(Left2 +10,Top2 -16);
	setPixel(Left2 +11,Top2 -16);
	setPixel(Left2 +12,Top2 -16);
	setPixel(Left2 +13,Top2 -16);
	setPixel(Left2 +14,Top2 -16);

	//Eigteenth Row
	setPixel(Left2 +3,Top2 -17);
	setPixel(Left2 +4,Top2 -17);
	setPixel(Left2 +9,Top2 -17);
	setPixel(Left2 +11,Top2 -17);
	setPixel(Left2 +12,Top2 -17);
	setPixel(Left2 +13,Top2 -17);
	setPixel(Left2 +14,Top2 -17);
	setPixel(Left2 +15,Top2 -17);
	setPixel(Left2 +19,Top2 -17);
	setPixel(Left2 +20,Top2 -17);
	setPixel(Left2 +21,Top2 -17);

	//Ninteenth Row
	setPixel(Left2 +9,Top2 -18);
	setPixel(Left2 +17,Top2 -18);
	setPixel(Left2 +19,Top2 -18);
	setPixel(Left2 +20,Top2 -18);
	setPixel(Left2 +21,Top2 -18);

	//Twenteeth Row
	setPixel(Left2 +8,Top2 -19);
	setPixel(Left2 +9,Top2 -19);
	setPixel(Left2 +14,Top2 -19);
	setPixel(Left2 +16,Top2 -19);
	setPixel(Left2 +17,Top2 -19);
	setPixel(Left2 +19,Top2 -19);
	setPixel(Left2 +20,Top2 -19);
	setPixel(Left2 +22,Top2 -19);
	setPixel(Left2 +23,Top2 -19);

	//TwenteeFirst Row
	setPixel(Left2 +8,Top2 -20);
	setPixel(Left2 +9,Top2 -20);
	setPixel(Left2 +13,Top2 -20);
	setPixel(Left2 +14,Top2 -20);
	setPixel(Left2 +15,Top2 -20);
	setPixel(Left2 +17,Top2 -20);
	setPixel(Left2 +18,Top2 -20);
	setPixel(Left2 +20,Top2 -20);
	setPixel(Left2 +21,Top2 -20);
	setPixel(Left2 +22,Top2 -20);
	setPixel(Left2 +23,Top2 -20);

	//22 Row
	setPixel(Left2 +8,Top2 -21);
	setPixel(Left2 +13,Top2 -21);
	setPixel(Left2 +14,Top2 -21);
	setPixel(Left2 +15,Top2 -21);
	setPixel(Left2 +17,Top2 -21);
	setPixel(Left2 +20,Top2 -21);
	setPixel(Left2 +21,Top2 -21);
	setPixel(Left2 +23,Top2 -21);

	//23 Row
	setPixel(Left2 +7,Top2 -22);
	setPixel(Left2 +8,Top2 -22);
	setPixel(Left2 +10,Top2 -22);
	setPixel(Left2 +11,Top2 -22);
	setPixel(Left2 +12,Top2 -22);
	setPixel(Left2 +14,Top2 -22);
	setPixel(Left2 +15,Top2 -22);
	setPixel(Left2 +17,Top2 -22);
	setPixel(Left2 +19,Top2 -22);
	setPixel(Left2 +22,Top2 -22);
	setPixel(Left2 +24,Top2 -22);

	//24 Row
	setPixel(Left2 +7,Top2 -23);
	setPixel(Left2 +8,Top2 -23);
	setPixel(Left2 +9,Top2 -23);
	setPixel(Left2 +12,Top2 -23);
	setPixel(Left2 +13,Top2 -23);
	setPixel(Left2 +14,Top2 -23);
	setPixel(Left2 +15,Top2 -23);
	setPixel(Left2 +17,Top2 -23);
	setPixel(Left2 +19,Top2 -23);
	setPixel(Left2 +20,Top2 -23);
	setPixel(Left2 +22,Top2 -23);
	setPixel(Left2 +23,Top2 -23);
	setPixel(Left2 +24,Top2 -23);

	//25 Row
	setPixel(Left2 +6,Top2 -24);
	setPixel(Left2 +7,Top2 -24);
	setPixel(Left2 +15,Top2 -24);
	setPixel(Left2 +17,Top2 -24);
	setPixel(Left2 +19,Top2 -24);
	setPixel(Left2 +20,Top2 -24);
	setPixel(Left2 +21,Top2 -24);
	setPixel(Left2 +23,Top2 -24);

	//26 Row
	setPixel(Left2 +5,Top2 -25);
	setPixel(Left2 +6,Top2 -25);
	setPixel(Left2 +13,Top2 -25);
	setPixel(Left2 +14,Top2 -25);
	setPixel(Left2 +15,Top2 -25);
	setPixel(Left2 +16,Top2 -25);
	setPixel(Left2 +18,Top2 -25);
	setPixel(Left2 +23,Top2 -25);

	//27 Row
	setPixel(Left2 +3,Top2 -26);
	setPixel(Left2 +4,Top2 -26);
	setPixel(Left2 +5,Top2 -26);
	setPixel(Left2 +12,Top2 -26);
	setPixel(Left2 +13,Top2 -26);
	setPixel(Left2 +14,Top2 -26);
	setPixel(Left2 +15,Top2 -26);
	setPixel(Left2 +16,Top2 -26);
	setPixel(Left2 +17,Top2 -26);
	setPixel(Left2 +19,Top2 -26);
	setPixel(Left2 +20,Top2 -26);
	setPixel(Left2 +21,Top2 -26);
	setPixel(Left2 +22,Top2 -26);

	//28 Row
	setPixel(Left2 +2,Top2 -27);
	setPixel(Left2 +3,Top2 -27);
	setPixel(Left2 +4,Top2 -27);
	setPixel(Left2 +11,Top2 -27);
	setPixel(Left2 +12,Top2 -27);
	setPixel(Left2 +13,Top2 -27);
	setPixel(Left2 +14,Top2 -27);
	setPixel(Left2 +17,Top2 -27);
	setPixel(Left2 +18,Top2 -27);
	setPixel(Left2 +21,Top2 -27);
	setPixel(Left2 +22,Top2 -27);

	//29 Row
	setPixel(Left2,Top2 -28);
	setPixel(Left2 +1,Top2 -28);
	setPixel(Left2 +2,Top2 -28);
	setPixel(Left2 +3,Top2 -28);
	setPixel(Left2 +18,Top2 -28);

	//Yeah finaly done!!!!!

}
void Del () {
	displayTextLine (1," ");
	displayTextLine(2," ");
	displayTextLine(3," ");
	displayTextLine(4," ");
	displayTextLine(5," ");
	sleep(2000);

}

void Text (string a, string b, string c, string d, string e) {

	displayTextLine(1,a);
	sleep(1000);
	displayTextLine(2,b);
	sleep(1000);
	displayTextLine(3,c);
	sleep(1000);
	displayTextLine(4,d);
	sleep(1000);
	displayTextLine(5,e);
	sleep(1500);
}

int N1 = 0;



string a = "Would you like to";
string aa = "Start the game??";
string ab = "  ";
string ac = "Click the green button";
string ad = "  ";

string ae = "The Beloved Emporor";
string af = "has fallen ill";
string ag = "and requires you";
string ah = "to obtain the";
string ai = "crystal flower from";

string aj = "The labyrinth";
string ak = "Do you accept???";
string al = "  ";
string am = "  ";
string an = "  ";

string ao = "Do you accept???";
string ap = "  ";
string aq = "  ";
string ar = "Yes  (Green).";
string as = "No thanks (Red).";

string at = "You politely decline";
string au = "In the end you survive";
string av = "As a consequence";
string aw = "Of your actions the";
string ax = "Emperor dies and";

string ay = "The kingdom falls";
string az = "Into chaos";
string ba = "  ";
string bb = "  ";
string bc = "  ";

string bd = "     Game Over!";
string be = "  ";
string bf = "     You Survived!";
string bg = "Have a lollipop";
string bh = "  ";

string bi = "As you head to the";
string bj = "Labyrinth you notice";
string bk = "That the further";
string bl = "You go the more";
string bm = "Dying and rotting";

string bn = "Trees there are, and";
string bo = "The sky blackens...";
string bp = "  ";
string bq = "You enter the";
string br = "Labyrinth and head";

string bs = "Straight you arrive";
string bt = "At a fork in the";
string bu = "Road and three";
string bv = "Paths open before you";
string bw = "On the first path";

string bx = "You can see wild";
string by = "Flowers Growing";
string bz = "Near the entrance";
string ca = "And you think you";
string cb = "See a blueberry patch";

string cc = "In the distance";
string cd = "  ";
string ce = "  ";
string cf = "  ";
string cg = "  ";

string ch = "At the entrance of";
string ci = "The second path you";
string cj = "See a discarded";
string ck = "Rusty longsword on";
string cl = "The ground";

string cm = "On the third and final";
string cn = "Path you can smell a";
string co = "Strange scent, like";
string cp = "Rotten meat or,";
string cq = "Something else";

string cr = "Which path shall you";
string cs = "Choose???";
string ct = "Path one  (Green)";
string cu = "Path two  (Blue)";
string cv = "Path three(Red)";

string cw = "Program too big";
string cx = "Error has ocurred";
string cy = "Continue on program";
string cz = "Path 1";
string da = "  ";

string cz2 = "Path 2";


string cz3 = "Path 3";


task main()
{
	setDistanceMaxRange(Distance, 300);


	Text(a,aa,ab,ac,ad);

	N1 = 0;
	while(getTouchLEDValue(Num1)== 0)
	{
		setTouchLEDRGB(Num1,0,255,0);
		setTouchLEDRGB(Num2,0,0,255);
		setTouchLEDRGB(Num3,255,0,0);

	}
	wait1Msec(1000);
	N1 = 0;



	//Labyrinth Game
	//If you decide not to go in you win!


	Del();

	Text(ae,af,ag,ah,ai);

	Del();

	Text(aj,ak,al,am,an);

	Del();
	Text(ao,ap,aq,ar,as);

	N1 = 0;

	Del();
	while(N1 == 0)
	{
		F2(Left2, Top2);
		setTouchLEDRGB(Num1,0,255,0);
		setTouchLEDRGB(Num3,255,0,0);


		if (getTouchLEDValue(Num1)== 1)

		N1 = N1 +1;




		if (getTouchLEDValue(Num3)== 1)
		{
			Del();

			Text(at,au,av,aw,ax);

			Del();

			Text(ay,az,ba,bb,bc);

			Del();

			Text(bd,be,bf,bg,bh);

		}
	}
	if (N1 == 1)
	{
		Del();

		Text(bi,bj,bk,bl,bm);

		Del();
	}
	Text(bn,bo,bp,bq,br);

	Del();

	Text(bs,bt,bu,bv,bw);

	Del();

	Text(bx,by,bz,ca,cb);

	Del();

	Text(cc,cd,ce,cf,cg);

	Del();
	//Second path choice
	Text(ch,ci,cj,ck,cl);

	Del();
	//Thrid choice path
	Text(cm,cn,co,cp,cq);

	Del();

	Text(cr,cs,ct,cu,cv);

	N1 = 0;
	//
	//
	// PAth ont two or three
	//
	//
	while(N1 == 0)
	{
		setTouchLEDRGB(Num1,0,255,0);
		setTouchLEDRGB(Num2,0,0,255);
		setTouchLEDRGB(Num3,255,0,0);

		if (getTouchLEDValue(Num1)== 1) {
			N1 = N1 +1;
		}
		if (getTouchLEDValue(Num2)== 1) {
			N1 = N1 +2;
		}
		if (getTouchLEDValue(Num3)== 1) {
			N1 = N1 +3;
		}
	}
	if (N1 == 1)
	{
		Del();

		Text(cw,cx,cy,cz,da);

		sleep(1500000000000000);

	}
	else if (N1 == 1)
	{
		Del();
		Text(cw,cx,cy,cz2,da);

		sleep(1500000000000000);

	}
	else if (N1 == 1)
	{
		Del();

		Text(cw,cx,cy,cz3,da);

		sleep(1500000000000000);

	}


}
