#pragma config(Sensor, port6,  Button,         sensorVexIQ_Touch)
#pragma config(Sensor, port7,  Num1,           sensorVexIQ_LED)
#pragma config(Sensor, port8,  Num2,           sensorVexIQ_LED)
#pragma config(Sensor, port9,  Num3,           sensorVexIQ_LED)
#pragma config(Sensor, port10, Gyro,           sensorVexIQ_Gyro)
#pragma config(Sensor, port11, Distance,       sensorVexIQ_Distance)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
int Left2 = 40;
int Top2 = 40;

void F2 (int Left2, int Top2)
{
	//is 29 tall
  //25 wide idk

//First row
setPixel(Left2 +9,Top2);
setPixel(Left2 +10,Top2);
setPixel(Left2 +11,Top2);
setPixel(Left2 +12,Top2);
setPixel(Left2 +13,Top2);

//Second Row
setPixel(Left2 +8,Top2 -1);
setPixel(Left2 +11,Top2 -1);
setPixel(Left2 +12,Top2 -1);
setPixel(Left2 +13,Top2 -1);

//Third Row
setPixel(Left2 +5,Top2 -2);
setPixel(Left2 +7,Top2 -2);
setPixel(Left2 +8,Top2 -2);
setPixel(Left2 +9,Top2 -2);
setPixel(Left2 +10,Top2 -2);
setPixel(Left2 +14,Top2 -2);
setPixel(Left2 +15,Top2 -2);
setPixel(Left2 +16,Top2 -2);

//Fourth Row
setPixel(Left2 +4,Top2 -3);
setPixel(Left2 +5,Top2 -3);
setPixel(Left2 +7,Top2 -3);
setPixel(Left2 +8,Top2 -3);
setPixel(Left2 +9,Top2 -3);
setPixel(Left2 +11,Top2 -3);
setPixel(Left2 +12,Top2 -3);
setPixel(Left2 +13,Top2 -3);
setPixel(Left2 +14,Top2 -3);
setPixel(Left2 +15,Top2 -3);
setPixel(Left2 +16,Top2 -3);

//Fifth Row
setPixel(Left2 +4,Top2 -4);
setPixel(Left2 +5,Top2 -4);
setPixel(Left2 +8,Top2 -4);
setPixel(Left2 +10,Top2 -4);
setPixel(Left2 +11,Top2 -4);
setPixel(Left2 +13,Top2 -4);
setPixel(Left2 +14,Top2 -4);
setPixel(Left2 +15,Top2 -4);
setPixel(Left2 +16,Top2 -4);

//Sixth Row
setPixel(Left2 +4,Top2 -5);
setPixel(Left2 +5,Top2 -5);
setPixel(Left2 +7,Top2 -5);
setPixel(Left2 +9,Top2 -5);
setPixel(Left2 +12,Top2 -5);
setPixel(Left2 +13,Top2 -5);
setPixel(Left2 +14,Top2 -5);

//Seventh Row
setPixel(Left2 +4,Top2 -6);
setPixel(Left2 +5,Top2 -6);
setPixel(Left2 +7,Top2 -6);
setPixel(Left2 +8,Top2 -6);
setPixel(Left2 +15,Top2 -6);
setPixel(Left2 +16,Top2 -6);
setPixel(Left2 +17,Top2 -6);

//Eigth Row
setPixel(Left2 +1,Top2 -7);
setPixel(Left2 +2,Top2 -7);
setPixel(Left2 +3,Top2 -7);
setPixel(Left2 +5,Top2 -7);
setPixel(Left2 +7,Top2 -7);
setPixel(Left2 +8,Top2 -7);
setPixel(Left2 +9,Top2 -7);
setPixel(Left2 +10,Top2 -7);
setPixel(Left2 +11,Top2 -7);
setPixel(Left2 +12,Top2 -7);
setPixel(Left2 +14,Top2 -7);
setPixel(Left2 +15,Top2 -7);
setPixel(Left2 +16,Top2 -7);
setPixel(Left2 +17,Top2 -7);
setPixel(Left2 +18,Top2 -7);

//Ninth Row
setPixel(Left2 +2,Top2 -8);
setPixel(Left2 +3,Top2 -8);
setPixel(Left2 +4,Top2 -8);
setPixel(Left2 +6,Top2 -8);
setPixel(Left2 +8,Top2 -8);
setPixel(Left2 +9,Top2 -8);
setPixel(Left2 +10,Top2 -8);
setPixel(Left2 +11,Top2 -8);
setPixel(Left2 +13,Top2 -8);
setPixel(Left2 +14,Top2 -8);
setPixel(Left2 +15,Top2 -8);
setPixel(Left2 +16,Top2 -8);
setPixel(Left2 +17,Top2 -8);
setPixel(Left2 +18,Top2 -8);

//Tenth Row
setPixel(Left2 +2,Top2 -9);
setPixel(Left2 +3,Top2 -9);
setPixel(Left2 +4,Top2 -9);
setPixel(Left2 +5,Top2 -9);
setPixel(Left2 +7,Top2 -9);
setPixel(Left2 +15,Top2 -9);
setPixel(Left2 +16,Top2 -9);
setPixel(Left2 +17,Top2 -9);

//Eleventh Row
setPixel(Left2 +3,Top2 -10);
setPixel(Left2 +4,Top2 -10);
setPixel(Left2 +5,Top2 -10);
setPixel(Left2 +6,Top2 -10);
setPixel(Left2 +8,Top2 -10);
setPixel(Left2 +9,Top2 -10);
setPixel(Left2 +10,Top2 -10);
setPixel(Left2 +11,Top2 -10);
setPixel(Left2 +12,Top2 -10);
setPixel(Left2 +13,Top2 -10);
setPixel(Left2 +14,Top2 -10);
setPixel(Left2 +16,Top2 -10);

//Twelth Row
setPixel(Left2 +4,Top2 -11);
setPixel(Left2 +5,Top2 -11);
setPixel(Left2 +6,Top2 -11);
setPixel(Left2 +7,Top2 -11);
setPixel(Left2 +9,Top2 -11);
setPixel(Left2 +10,Top2 -11);
setPixel(Left2 +11,Top2 -11);
setPixel(Left2 +12,Top2 -11);
setPixel(Left2 +13,Top2 -11);
setPixel(Left2 +14,Top2 -11);
setPixel(Left2 +15,Top2 -11);

//Thirteenth Row
setPixel(Left2 +12,Top2 -12);
setPixel(Left2 +13,Top2 -12);
setPixel(Left2 +14,Top2 -12);
setPixel(Left2 +15,Top2 -12);

//Fourteenth Row
setPixel(Left2 +4,Top2 -13);
setPixel(Left2 +5,Top2 -13);
setPixel(Left2 +6,Top2 -13);
setPixel(Left2 +7,Top2 -13);
setPixel(Left2 +8,Top2 -13);
setPixel(Left2 +10,Top2 -13);
setPixel(Left2 +11,Top2 -13);
setPixel(Left2 +14,Top2 -13);

//Fifteenth Row
setPixel(Left2 +3,Top2 -14);
setPixel(Left2 +4,Top2 -14);
setPixel(Left2 +5,Top2 -14);
setPixel(Left2 +6,Top2 -14);
setPixel(Left2 +7,Top2 -14);
setPixel(Left2 +9,Top2 -14);
setPixel(Left2 +10,Top2 -14);
setPixel(Left2 +11,Top2 -14);
setPixel(Left2 +12,Top2 -14);

//Sixteenth Row
setPixel(Left2 +3,Top2 -15);
setPixel(Left2 +4,Top2 -15);
setPixel(Left2 +5,Top2 -15);
setPixel(Left2 +6,Top2 -15);
setPixel(Left2 +7,Top2 -15);
setPixel(Left2 +9,Top2 -15);
setPixel(Left2 +10,Top2 -15);
setPixel(Left2 +11,Top2 -15);
setPixel(Left2 +12,Top2 -15);
setPixel(Left2 +13,Top2 -15);

//Seventeenth Row
setPixel(Left2 +3,Top2 -16);
setPixel(Left2 +4,Top2 -16);
setPixel(Left2 +5,Top2 -16);
setPixel(Left2 +6,Top2 -16);
setPixel(Left2 +9,Top2 -16);
setPixel(Left2 +10,Top2 -16);
setPixel(Left2 +11,Top2 -16);
setPixel(Left2 +12,Top2 -16);
setPixel(Left2 +13,Top2 -16);
setPixel(Left2 +14,Top2 -16);

//Eigteenth Row
setPixel(Left2 +3,Top2 -17);
setPixel(Left2 +4,Top2 -17);
setPixel(Left2 +9,Top2 -17);
setPixel(Left2 +11,Top2 -17);
setPixel(Left2 +12,Top2 -17);
setPixel(Left2 +13,Top2 -17);
setPixel(Left2 +14,Top2 -17);
setPixel(Left2 +15,Top2 -17);
setPixel(Left2 +19,Top2 -17);
setPixel(Left2 +20,Top2 -17);
setPixel(Left2 +21,Top2 -17);

//Ninteenth Row
setPixel(Left2 +9,Top2 -18);
setPixel(Left2 +17,Top2 -18);
setPixel(Left2 +19,Top2 -18);
setPixel(Left2 +20,Top2 -18);
setPixel(Left2 +21,Top2 -18);

//Twenteeth Row
setPixel(Left2 +8,Top2 -19);
setPixel(Left2 +9,Top2 -19);
setPixel(Left2 +14,Top2 -19);
setPixel(Left2 +16,Top2 -19);
setPixel(Left2 +17,Top2 -19);
setPixel(Left2 +19,Top2 -19);
setPixel(Left2 +20,Top2 -19);
setPixel(Left2 +22,Top2 -19);
setPixel(Left2 +23,Top2 -19);

//TwenteeFirst Row
setPixel(Left2 +8,Top2 -20);
setPixel(Left2 +9,Top2 -20);
setPixel(Left2 +13,Top2 -20);
setPixel(Left2 +14,Top2 -20);
setPixel(Left2 +15,Top2 -20);
setPixel(Left2 +17,Top2 -20);
setPixel(Left2 +18,Top2 -20);
setPixel(Left2 +20,Top2 -20);
setPixel(Left2 +21,Top2 -20);
setPixel(Left2 +22,Top2 -20);
setPixel(Left2 +23,Top2 -20);

//22 Row
setPixel(Left2 +8,Top2 -21);
setPixel(Left2 +13,Top2 -21);
setPixel(Left2 +14,Top2 -21);
setPixel(Left2 +15,Top2 -21);
setPixel(Left2 +17,Top2 -21);
setPixel(Left2 +20,Top2 -21);
setPixel(Left2 +21,Top2 -21);
setPixel(Left2 +23,Top2 -21);

//23 Row
setPixel(Left2 +7,Top2 -22);
setPixel(Left2 +8,Top2 -22);
setPixel(Left2 +10,Top2 -22);
setPixel(Left2 +11,Top2 -22);
setPixel(Left2 +12,Top2 -22);
setPixel(Left2 +14,Top2 -22);
setPixel(Left2 +15,Top2 -22);
setPixel(Left2 +17,Top2 -22);
setPixel(Left2 +19,Top2 -22);
setPixel(Left2 +22,Top2 -22);
setPixel(Left2 +24,Top2 -22);

//24 Row
setPixel(Left2 +7,Top2 -23);
setPixel(Left2 +8,Top2 -23);
setPixel(Left2 +9,Top2 -23);
setPixel(Left2 +12,Top2 -23);
setPixel(Left2 +13,Top2 -23);
setPixel(Left2 +14,Top2 -23);
setPixel(Left2 +15,Top2 -23);
setPixel(Left2 +17,Top2 -23);
setPixel(Left2 +19,Top2 -23);
setPixel(Left2 +20,Top2 -23);
setPixel(Left2 +22,Top2 -23);
setPixel(Left2 +23,Top2 -23);
setPixel(Left2 +24,Top2 -23);

//25 Row
setPixel(Left2 +6,Top2 -24);
setPixel(Left2 +7,Top2 -24);
setPixel(Left2 +15,Top2 -24);
setPixel(Left2 +17,Top2 -24);
setPixel(Left2 +19,Top2 -24);
setPixel(Left2 +20,Top2 -24);
setPixel(Left2 +21,Top2 -24);
setPixel(Left2 +23,Top2 -24);

//26 Row
setPixel(Left2 +5,Top2 -25);
setPixel(Left2 +6,Top2 -25);
setPixel(Left2 +13,Top2 -25);
setPixel(Left2 +14,Top2 -25);
setPixel(Left2 +15,Top2 -25);
setPixel(Left2 +16,Top2 -25);
setPixel(Left2 +18,Top2 -25);
setPixel(Left2 +23,Top2 -25);

//27 Row
setPixel(Left2 +3,Top2 -26);
setPixel(Left2 +4,Top2 -26);
setPixel(Left2 +5,Top2 -26);
setPixel(Left2 +12,Top2 -26);
setPixel(Left2 +13,Top2 -26);
setPixel(Left2 +14,Top2 -26);
setPixel(Left2 +15,Top2 -26);
setPixel(Left2 +16,Top2 -26);
setPixel(Left2 +17,Top2 -26);
setPixel(Left2 +19,Top2 -26);
setPixel(Left2 +20,Top2 -26);
setPixel(Left2 +21,Top2 -26);
setPixel(Left2 +22,Top2 -26);

//28 Row
setPixel(Left2 +2,Top2 -27);
setPixel(Left2 +3,Top2 -27);
setPixel(Left2 +4,Top2 -27);
setPixel(Left2 +11,Top2 -27);
setPixel(Left2 +12,Top2 -27);
setPixel(Left2 +13,Top2 -27);
setPixel(Left2 +14,Top2 -27);
setPixel(Left2 +17,Top2 -27);
setPixel(Left2 +18,Top2 -27);
setPixel(Left2 +21,Top2 -27);
setPixel(Left2 +22,Top2 -27);

//29 Row
setPixel(Left2,Top2 -28);
setPixel(Left2 +1,Top2 -28);
setPixel(Left2 +2,Top2 -28);
setPixel(Left2 +3,Top2 -28);
setPixel(Left2 +18,Top2 -28);

//Yeah finaly done!!!!!

}
void Del () {
	displayTextLine(1," ");
	displayTextLine(2," ");
	displayTextLine(3," ");
	displayTextLine(4," ");
	displayTextLine(5," ");
	sleep(2000);

}
int N1 = 0;
int Crystal = 0;
int Count = 0;
int Hits = 0;
int Final = 0;
int CL = 0;
int Gold = 0;
int Dist = 0;
int Die  = 0;
int Dodge = 0;
int Touch = 0;
int Degree = getGyroDegrees(Gyro);
task main()
{
	setTouchLEDRGB(Num1,0,255,0);
	setTouchLEDRGB(Num2,0,0,255);
	setTouchLEDRGB(Num3,255,0,0);

	N1 = 0;

	Del();

	displayTextLine(1,"As you continue");
	sleep(1000);
	displayTextLine(2,"You begin to hear");
	sleep(1000);
	displayTextLine(3,"Hard breathing");
	sleep(1000);
	displayTextLine(4,"And loud thuds");
	sleep(1000);
	displayTextLine(5,"Behind you.");
	sleep(2000);

	Del();

	displayTextLine(1,"You turn around to");
	sleep(1000);
	displayTextLine(2,"And stop to check");
	sleep(1000);
	displayTextLine(3,"Nothing. ");
	sleep(1000);
	displayTextLine(4,"You start walking again.");
	sleep(1000);
	displayTextLine(5,"The sounds continue");
	sleep(2000);

	Del();

	displayTextLine(1,"Aswell.");
	sleep(1000);
	displayTextLine(2,"The noise starts");
	sleep(1000);
	displayTextLine(3,"Accelerating");
	sleep(1000);
	displayTextLine(4,"You turn around");
	sleep(1000);
	displayTextLine(5,"This time you see");
	sleep(2500);

	Del();

	displayTextLine(1,"A Man with a bulls ");
	sleep(1000);
	displayTextLine(2,"Head charging at you");
	sleep(100);
	displayTextLine(3,"");
	sleep(100);
	displayTextLine(4,"");
	sleep(100);
	displayTextLine(5,"");
	sleep(2500);

	Del();

	displayTextLine(1,"What shall you do?");
	sleep(1000);
	displayTextLine(2,"(Be quick)");
	sleep(1000);
	displayTextLine(3,"RUN AWAY! (Green)");
	sleep(1000);
	displayTextLine(4,"BULLFIGHT!(Blue)");
	sleep(1000);
	displayTextLine(5,"FIGHT!!!  (Red)");
	sleep(250);



	Count = 0;
	N1 = 0;
	Final = 0;
	//
	//Run, Fight or Bullfight Minotaur
	//

	while (N1 == 0)
	{
		setTouchLEDRGB(Num1,0,255,0);
		setTouchLEDRGB(Num2,0,0,255);
		setTouchLEDRGB(Num3,255,0,0);

		if (getTouchLEDValue(Num1) == 1)
		{
			N1 = 1;
			Touch = 1;
		}
		if (getTouchLEDValue(Num2) == 1)
		{
			N1 = 2;
			Final = 1;
			Touch = 1;
		}
		if (getTouchLEDValue(Num3) == 1)
		{
			N1 = 3;
			Final = 2;
			Touch = 1;
		}
	}

	//
	//Run away
	//
	if (N1 == 1)
	{
		Del();

		displayTextLine(1,"You start to run");
		sleep(1000);
		displayTextLine(2,"Away from the");
		sleep(1000);
		displayTextLine(3,"Minotaur but it");
		sleep(1000);
		displayTextLine(4,"Quickly catches up");
		sleep(1000);
		displayTextLine(5,"And kills you");
		sleep(2500);

		Del();

		displayTextLine(1,"Your smashed on the");
		sleep(1000);
		displayTextLine(2,"Wall");
		sleep(1000);
		displayTextLine(3,"   GAME OVER!");
		sleep(1000);
		displayTextLine(4,"You died. I said be");
		sleep(1000);
		displayTextLine(5,"Quick I meant it");
		sleep(2500000000000000000000000);
	}
	//
	//Bullfight Minotaur
	//
	if (N1 == 2)
	{
   Final = 0;
		Del();

		displayTextLine(1,"You choose to");
		sleep(1000);
		displayTextLine(2,"Bullfight the");
		sleep(1000);
		displayTextLine(3,"Minotaur ");
		sleep(1000);
		displayTextLine(4,"When it says turn");
		sleep(1000);
		displayTextLine(5,"The console to the");
		sleep(2500);

		Del();

		displayTextLine(1,"Degree it wants");
		sleep(1000);
		displayTextLine(2,"You have 3 seconds");
		sleep(1000);
		displayTextLine(3,"To dodge it");
		sleep(1000);
		displayTextLine(4,"Turn to 90 Degrees");
		sleep(1000);
		displayTextLine(5,"(Left) Now!!");
		sleep(250);

		Del();
		displayTextLine(1,"90 Degrees");
		displayTextLine(2,"(Turn Left)");
		Count = 0;
		N1 = 0;
		Dodge = 0;
		resetGyro(Gyro);

		while (Count <= 300)
		{
			Degree = getGyroDegrees(Gyro);
			displayTextLine(1,"Degree: %d", Degree);
			if (getGyroDegrees(Gyro) <= 100)
			{
				if (getGyroDegrees(Gyro) >= 80)
				{
					Dodge = 1;

				}
			}
			Count += 1;
			wait1Msec(10);
		}
		//
		//Too slow
		//
		if (Dodge == 0)
			Die = 1;

		if (Dodge == 1)
		{
			Del();

			displayTextLine(1,"You dodge it but");
			sleep(1000);
			displayTextLine(2,"It charges at you ");
			sleep(1000);
			displayTextLine(3,"Again");
			sleep(1000);
			displayTextLine(4,"Turn to -90 Degrees");
			sleep(1000);
			displayTextLine(5,"(Right) Now!!");
			sleep(250);

			Del();
			displayTextLine(1,"-90 Degrees");
			displayTextLine(2,"(Turn Right)");
			Count = 0;
			N1 = 0;
			Dodge = 0;
			resetGyro(Gyro);

			while (Count <= 300)
			{
				Degree = getGyroDegrees(Gyro);
				displayTextLine(1,"Degree: %d", Degree);
				if (getGyroDegrees(Gyro) >= -100)
				{
					if (getGyroDegrees(Gyro) <= -80)
					{
						Dodge = 1;

					}
				}
				Count += 1;
				wait1Msec(10);
			}
			//
			//Too slow
			//
			if (Dodge == 0)
				Die = 1;
			//
			//Second dodge
			//
			if (Dodge == 1)
			{
				Del();

				displayTextLine(1,"You dodge it");
				sleep(1000);
				displayTextLine(2,"One last time now");
				sleep(1000);
				displayTextLine(3,"Again");
				sleep(1000);
				displayTextLine(4,"Turn to 180 Degrees");
				sleep(1000);
				displayTextLine(5,"(Left ) Now!!");
				sleep(250);

				Del();
				displayTextLine(1,"180 Degrees");
				displayTextLine(2,"(Turn Left)");
				Count = 0;
				N1 = 0;
				Dodge = 0;
				resetGyro(Gyro);

				while (Count <= 300)
				{
					Degree = getGyroDegrees(Gyro);
					displayTextLine(1,"Degree: %d", Degree);
					if (getGyroDegrees(Gyro) <= 190)
					{
						if (getGyroDegrees(Gyro) >= 170)
							Dodge = 1;

					}
					Count += 1;
					wait1Msec(10);
				}
			}
			//
			//Too slow
			//
			if (Dodge == 0)
				Die = 1;

			//
			//Died
			//
			if (Die == 1)
			{
				Del();

				displayTextLine(1,"Your smashed into the");
				sleep(1000);
				displayTextLine(2,"Wall");
				sleep(1000);
				displayTextLine(3,"   GAME OVER!");
				sleep(1000);
				displayTextLine(4,"You died. I said be");
				sleep(1000);
				displayTextLine(5,"Quick I meant it");
				sleep(2500000000000000000000000);
			}
			if (Dodge == 1)
				Final = 1;

		}
	}
	//
	//Fight Minotaur
	//
	if (N1 == 3)
	{
		Final = 0;
		Die = 0;
		Del();

		displayTextLine(1,"You turn around and");
		sleep(1000);
		displayTextLine(2,"Fight the Minotaur");
		sleep(1000);
		displayTextLine(3,"(Hit it 300 times)");
		sleep(1000);
		displayTextLine(4,"(In 5 seconds)");
		sleep(1000);
		displayTextLine(5,"...");
		sleep(2500);

		Del();

		displayTextLine(1,"Now!!");
		Count = 0;
		Hits = 0;
		CL = 0;

		while(Count <= 500)
		{
			if (getBumperValue(Button)== 1)
				Hits +=1;
			if (Hits >= 300)
				CL = 1;
			displayTextLine(3,"Hits: %d",Hits);
			Count +=1;
			wait1Msec(10);
		}
		//
		//Kill 1
		//
		if (CL == 1)
		{
			Del();

			displayTextLine(1,"You get one of its");
			sleep(1000);
			displayTextLine(2,"Arms. Now for its");
			sleep(1000);
			displayTextLine(3,"Second Arm");
			sleep(1000);
			displayTextLine(4,"");
			sleep(100);
			displayTextLine(5,"...");
			sleep(2500);

			Del();

			displayTextLine(1,"Now!!");
			Count = 0;
			Hits = 0;
			CL = 0;
			//
			//Second arm fight
			//
			while(Count <= 500)
			{
				if (getBumperValue(Button)== 1)
					Hits +=1;
				if (Hits >= 300)
					CL = 1;
			displayTextLine(3,"Hits: %d",Hits);
				Count +=1;
				wait1Msec(10);
			}
			//
			//Kill 2
			//
			if (CL == 1)
			{
				Del();

				displayTextLine(1,"You get its second");
				sleep(1000);
				displayTextLine(2,"Arm. Now for its");
				sleep(1000);
				displayTextLine(3,"Head");
				sleep(1000);
				displayTextLine(4,"");
				sleep(100);
				displayTextLine(5,"...");
				sleep(2500);

				Del();

				displayTextLine(1,"Now!!");
				Count = 0;
				Hits = 0;
				CL = 0;
				//
				//Second fight Head
				//
				while(Count <= 500)
				{
					if (getBumperValue(Button)== 1)
						Hits +=1;
					if (Hits >= 300)
						CL = 1;
					displayTextLine(3,"Hits: %d",Hits);
					Count +=1;
					wait1Msec(10);
				}
				//
				//Kill Minotaur
				//
				if (CL == 1)
					Final = 2;
			}
		}
		//
		//You die
		//
		if (CL == 0)
			Die = 1;
		//
		//
		//Continue on
		//
		//
	}
	if (Final == 1 || Final == 2)
	{
		N1 = 0;
		Final = 0;
		Del();

		displayTextLine(1,"You continue");
		sleep(1000);
		displayTextLine(2,"Forward through");
		sleep(1000);
		displayTextLine(3,"And find a small");
		sleep(1000);
		displayTextLine(4,"Door. You look ");
		sleep(1000);
		displayTextLine(5,"Through it");
		sleep(2500);

		Del();

		displayTextLine(1,"It's pitch black ");
		sleep(1000);
		displayTextLine(2,"With only a small ");
		sleep(1000);
		displayTextLine(3,"Light in the distance");
		sleep(1000);
		displayTextLine(4,"You enter the door");
		sleep(1000);
		displayTextLine(5,"And it shuts behind");
		sleep(2500);

		Del();

		displayTextLine(1,"You and continue");
		sleep(1000);
		displayTextLine(2,"Walking forward arms");
		sleep(1000);
		displayTextLine(3,"Out stretched in");
		sleep(1000);
		displayTextLine(4,"Front of you to");
		sleep(1000);
		displayTextLine(5,"Not run into anything.");
		sleep(2500);

		Del();

		displayTextLine(1,"Eventually the light");
		sleep(1000);
		displayTextLine(2,"Is near you and in a");
		sleep(1000);
		displayTextLine(3,"Massive cavern with");
		sleep(1000);
		displayTextLine(4,"Alot of strange rocks");
		sleep(1000);
		displayTextLine(5,"Lining on the walls");
		sleep(2500);

		Del();

		displayTextLine(1,"You inspect them and");
		sleep(1000);
		displayTextLine(2,"Find out they are ");
		sleep(1000);
		displayTextLine(3,"Skulls on the back ");
		sleep(1000);
		displayTextLine(4,"Wall there is a ");
		sleep(1000);
		displayTextLine(5,"Imense door with ");
		sleep(2500);

		Del();

		displayTextLine(1," Writing on it. ");
		sleep(1000);
		displayTextLine(2,"It reads.");
		sleep(1000);
		displayTextLine(3,"");
		sleep(100);
		displayTextLine(4,"");
		sleep(100);
		displayTextLine(5,"");
		sleep(250);

		Del();

		displayTextLine(1,"I AM SEEN IN THE WATER");
		sleep(1000);
		displayTextLine(2,"IF SEEN IN THE SKY,");
		sleep(1000);
		displayTextLine(3,"I'M IN THE RAINBOW,");
		sleep(1000);
		displayTextLine(4,"A JAY'S FEATHER");
		sleep(1000);
		displayTextLine(5,"AND LAPIS LAZULI");
		sleep(2500);

		Del();

		displayTextLine(1,"");
		sleep(1000);
		displayTextLine(2,"-What could it mean-");
		sleep(1000);
		displayTextLine(3,"You think out loud");
		sleep(1000);
		displayTextLine(4,"");
		sleep(100);
		displayTextLine(5,"");
		sleep(250);

		//
		//BLUE COLOR TAP
		//
		while(N1 == 0)
		{
			if (getTouchLEDValue(Num2) == 1)
				N1 = 1;
		}
		//
		//Button click led
		//
		Del();

		displayTextLine(1,"You say out loud");
		sleep(1000);
		displayTextLine(2,"'BLUE'");
		sleep(1000);
		displayTextLine(3,"The door opens");
		sleep(1000);
		displayTextLine(4,"And you continue");
		sleep(1000);
		displayTextLine(5,"On the other side");
		sleep(2500);

		Del();

		displayTextLine(1,"You find a small");
		sleep(1000);
		displayTextLine(2,"Pond with turquoise ");
		sleep(1000);
		displayTextLine(3,"Water in it a vase ");
		sleep(1000);
		displayTextLine(4,"With...");
		sleep(1000);
		displayTextLine(5,"THE CRYSTAL FLOWER!");
		sleep(2500);

		Del();

		displayTextLine(1,"(Grab the crystal ");
		sleep(1000);
		displayTextLine(2,"Flower in the pond)");
		sleep(1000);
		displayTextLine(3,"(15 cm)");
		sleep(1000);
		displayTextLine(4,"");
		sleep(100);
		displayTextLine(5,"");
		sleep(250);

		Del();
		Crystal = 0;
		Dist = 0;
		while(Crystal == 0)
		{
			Dist = getDistanceValue(Distance);
			if (getDistanceValue(Distance) <170)
			{
				if (getDistanceValue(Distance) > 150)
				{
					Crystal = 1;
				}
			}
			displayTextLine(3,"Distance: %d",Dist);
		}
	}

	//
	//Grab flower
	//
	if (Crystal == 1)
	{
		Del();

		F2(Left2, Top2);

		displayTextLine(1,"You grab the flower and");
		sleep(1000);
		displayTextLine(2,"Are teleported ");
		sleep(1000);
		displayTextLine(3,"Outside The maze. 50000");
		sleep(1000);
		displayTextLine(4," Years");
		sleep(1000);
		displayTextLine(5,"Have passed...");
		sleep(2500);

		Del();

		displayTextLine(1,"LOL JK");
		sleep(1000);
		displayTextLine(2,"A door opens in the ");
		sleep(1000);
		displayTextLine(3,"Back of the room and");
		sleep(1000);
		displayTextLine(4,"You go through it");
		sleep(1000);
		displayTextLine(5,"You return home to ");
		sleep(2500);

		Del();

		displayTextLine(1,"The Emporor to give ");
		sleep(1000);
		displayTextLine(2,"Him the Flower. A ");
		sleep(1000);
		displayTextLine(3,"Huge parade awaits ");
		sleep(1000);
		displayTextLine(4,"For you, the ");
		sleep(1000);
		displayTextLine(5,"Savior of The Emporor");
		sleep(2500);

		Del();

		displayTextLine(1,"When you aproach his");
		sleep(1000);

		Del();

		displayTextLine(1,"Carage there are multiple");
		sleep(1000);
		displayTextLine(2,"Chests filled with gold.");
		sleep(1000);
		displayTextLine(3,"You decline but he insists");
		sleep(1000);
		displayTextLine(4,"The Emporor also appoints");
		sleep(1000);
		displayTextLine(5,"You as his next heir ");
		sleep(2500);

		Del();

		displayTextLine(1,"Your future is looking");
		sleep(1000);
		displayTextLine(2,"Great and is set in");
		sleep(1000);
		displayTextLine(3,"Stone. ");
		sleep(1000);
		displayTextLine(4,"");
		sleep(100);
		displayTextLine(5,"");
		sleep(2500);

		Del();

		displayTextLine(1,"Good job, You win");
		sleep(1000);
		displayTextLine(2,"We won't give you a ");
		sleep(1000);
		displayTextLine(3,"Useless digital certificate");
		sleep(1000);
		displayTextLine(4,"Like Pokémon does");
		sleep(1000);
		displayTextLine(5,"You beat the GAME");
		sleep(2500);

		Del();

		displayTextLine(1,"Again good job");
		sleep(1000);
		displayTextLine(2,"Tell the creators DNA");
		sleep(1000);
		displayTextLine(3,"And Alwyn if you want ");
		sleep(1000);
		displayTextLine(4,"A sequel. And rate game");
		sleep(1000);
		displayTextLine(5,"");
		sleep(2500);


		while(true)
		{
			Gold += 11;
			displayTextLine(5,"Gold: %d", Gold);


		}



		//
		//Die fighting or something
		//
		if (Die == 1)
		{
			Del();

			displayTextLine(1,"Your crushed on the");
			sleep(1000);
			displayTextLine(2,"Wall");
			sleep(1000);
			displayTextLine(3,"   GAME OVER!");
			sleep(1000);
			displayTextLine(4,"You died. Better");
			sleep(1000);
			displayTextLine(5,"Luck next time");
			sleep(2500000000000000000000000);



		}
		//
		//Too slow
		//
		if (N1 == 0 && Touch == 0)
		{
			Del();

			displayTextLine(1,"Your smashed on the");
			sleep(1000);
			displayTextLine(2,"Wall");
			sleep(1000);
			displayTextLine(3,"   GAME OVER!");
			sleep(1000);
			displayTextLine(4,"You died. I said be");
			sleep(1000);
			displayTextLine(5,"Quick I meant it");
			sleep(2500000000000000000000000);

		}


	}
}
