#pragma config(Motor,  port2,           Motor,         tmotorVex393HighSpeed_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true)
	{

		if (getJoystickValue(Ch3) > 20)
		{
			setMotorSpeed(Motor,50);
		} else if (getJoystickValue(Ch3) < -20)
		{
			setMotorSpeed(Motor, -50);
		}


	}
}
