#pragma config(Sensor, port1,  Gyro1,          sensorVexIQ_Gyro)
#pragma config(Sensor, port2,  Gyro2,          sensorVexIQ_Gyro)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
//Gyro 1 is N S W E
//Gyro 2 is up down front back
int ShipTop;
int ShipL;
void EMissile(int EMT, int EML)
{
	setPixel(EML,EMT- 4);
	setPixel(EML,EMT- 5);
	//Left Head of enemy missile
	setPixel(EML+ 1,EMT);
	setPixel(EML+ 1,EMT- 1);
	setPixel(EML+ 1,EMT- 2);
	setPixel(EML+ 1,EMT- 3);
	setPixel(EML+ 1,EMT- 4);
	setPixel(EML+ 1,EMT- 5);
	//Middle Row
	setPixel(EML+ 2,EMT- 4);
	setPixel(EML+ 2,EMT- 5);
	//Third Left Row
}
void Missile(int MTop, int ML)
{
	//Missile is 6 tall and 3 wide.

	setPixel(ML,MTop- 1);
	setPixel(ML,MTop- 2);
	//Left Head of Missile/ First Left Row
	setPixel(ML+ 1,MTop);
	setPixel(ML+ 1,MTop- 1);
	setPixel(ML+ 1,MTop- 2);
	setPixel(ML+ 1,MTop- 3);
	setPixel(ML+ 1,MTop- 4);
	setPixel(ML+ 1,MTop- 5);
	//Full length/ Middle Row of Missile/ Second Left Row
	setPixel(ML+ 2,MTop- 1);
	setPixel(ML+ 2,MTop- 2);
	//Right side Of Missile Head/ Third Left Row
}
void Ship (int ShipTop, int ShipL)
{
	//Gallaga Ship is 19 tall and 17 wide


	//All Comments about rows are the code above them
	setPixel(ShipL,ShipTop- 18);
	setPixel(ShipL,ShipTop- 17);
	setPixel(ShipL,ShipTop- 16);
	setPixel(ShipL,ShipTop- 15);
	setPixel(ShipL,ShipTop- 14);
	setPixel(ShipL,ShipTop- 13);
	setPixel(ShipL,ShipTop- 12);
	setPixel(ShipL,ShipTop- 11);
	setPixel(ShipL,ShipTop- 10);
	setPixel(ShipL,ShipTop- 9);
	setPixel(ShipL,ShipTop- 8);
	//First Left Row
	setPixel(ShipL + 1,ShipTop- 16);
	setPixel(ShipL + 1,ShipTop- 15);
	setPixel(ShipL + 1,ShipTop- 14);
	setPixel(ShipL + 1,ShipTop- 13);
	//Second Left Row
	setPixel(ShipL + 2,ShipTop- 15);
	setPixel(ShipL + 2,ShipTop- 14);
	setPixel(ShipL + 2,ShipTop- 13);
	setPixel(ShipL + 2,ShipTop- 12);
	//Third Left Row
	setPixel(ShipL + 3,ShipTop- 14);
	setPixel(ShipL + 3,ShipTop- 13);
	setPixel(ShipL + 3,ShipTop- 12);
	setPixel(ShipL + 3,ShipTop- 11);
	//Fourth Left Row
	setPixel(ShipL + 4,ShipTop- 13);
	setPixel(ShipL + 4,ShipTop- 12);
	setPixel(ShipL + 4,ShipTop- 11);
	setPixel(ShipL + 4,ShipTop- 10);
	setPixel(ShipL + 4,ShipTop- 9);
	setPixel(ShipL + 4,ShipTop- 8);
	setPixel(ShipL + 4,ShipTop- 7);
	setPixel(ShipL + 4,ShipTop- 6);
	setPixel(ShipL + 4,ShipTop- 5);
	//Fifth Left Row
	setPixel(ShipL + 5,ShipTop- 16);
	setPixel(ShipL + 5,ShipTop- 15);
	setPixel(ShipL + 5,ShipTop- 14);
	setPixel(ShipL + 5,ShipTop- 13);
	setPixel(ShipL + 5,ShipTop- 12);
	setPixel(ShipL + 5,ShipTop- 11);
	setPixel(ShipL + 5,ShipTop- 10);
	setPixel(ShipL + 5,ShipTop- 9);
	//Sixth Left Row
	setPixel(ShipL + 6,ShipTop- 16);
	setPixel(ShipL + 6,ShipTop- 15);
	setPixel(ShipL + 6,ShipTop- 14);
	setPixel(ShipL + 6,ShipTop- 13);
	setPixel(ShipL + 6,ShipTop- 12);
	setPixel(ShipL + 6,ShipTop- 11);
	setPixel(ShipL + 6,ShipTop- 10);
	setPixel(ShipL + 6,ShipTop- 9);
	setPixel(ShipL + 6,ShipTop- 8);
	//Seventh Left Row
	setPixel(ShipL + 7,ShipTop- 15);
	setPixel(ShipL + 7,ShipTop- 14);
	setPixel(ShipL + 7,ShipTop- 13);
	setPixel(ShipL + 7,ShipTop- 12);
	setPixel(ShipL + 7,ShipTop- 11);
	setPixel(ShipL + 7,ShipTop- 10);
	setPixel(ShipL + 7,ShipTop- 9);
	setPixel(ShipL + 7,ShipTop- 8);
	setPixel(ShipL + 7,ShipTop- 7);
	setPixel(ShipL + 7,ShipTop- 6);
	setPixel(ShipL + 7,ShipTop- 5);
	setPixel(ShipL + 7,ShipTop- 4);
	setPixel(ShipL + 7,ShipTop- 3);
	//8th Left Row
	setPixel(ShipL + 8,ShipTop- 18);
	setPixel(ShipL + 8,ShipTop- 17);
	setPixel(ShipL + 8,ShipTop- 16);
	setPixel(ShipL + 8,ShipTop- 15);
	setPixel(ShipL + 8,ShipTop- 14);
	setPixel(ShipL + 8,ShipTop- 13);
	setPixel(ShipL + 8,ShipTop- 12);
	setPixel(ShipL + 8,ShipTop- 11);
	setPixel(ShipL + 8,ShipTop- 10);
	setPixel(ShipL + 8,ShipTop- 9);
	setPixel(ShipL + 8,ShipTop- 8);
	setPixel(ShipL + 8,ShipTop- 7);
	setPixel(ShipL + 8,ShipTop- 6);
	setPixel(ShipL + 8,ShipTop- 5);
	setPixel(ShipL + 8,ShipTop- 4);
	setPixel(ShipL + 8,ShipTop- 3);
	setPixel(ShipL + 8,ShipTop- 2);
	setPixel(ShipL + 8,ShipTop- 1);
	setPixel(ShipL + 8,ShipTop);
	//Middle Row omg... Were only half way theeeerre OOOhhhh oohhhh Living on a prayer
	setPixel(ShipL +9,ShipTop- 15);
	setPixel(ShipL +9,ShipTop- 14);
	setPixel(ShipL +9,ShipTop- 13);
	setPixel(ShipL +9,ShipTop- 12);
	setPixel(ShipL +9,ShipTop- 11);
	setPixel(ShipL +9,ShipTop- 10);
	setPixel(ShipL +9,ShipTop- 9);
	setPixel(ShipL +9,ShipTop- 8);
	setPixel(ShipL +9,ShipTop- 7);
	setPixel(ShipL +9,ShipTop- 6);
	setPixel(ShipL +9,ShipTop- 5);
	setPixel(ShipL +9,ShipTop- 4);
	setPixel(ShipL +9,ShipTop- 3);
	//Ninth Left Row
	setPixel(ShipL +10,ShipTop- 16);
	setPixel(ShipL +10,ShipTop- 15);
	setPixel(ShipL +10,ShipTop- 14);
	setPixel(ShipL +10,ShipTop- 13);
	setPixel(ShipL +10,ShipTop- 12);
	setPixel(ShipL +10,ShipTop- 11);
	setPixel(ShipL +10,ShipTop- 10);
	setPixel(ShipL +10,ShipTop- 9);
	setPixel(ShipL +10,ShipTop- 8);
	//Tenth Left Row
	setPixel(ShipL +11,ShipTop- 16);
	setPixel(ShipL +11,ShipTop- 15);
	setPixel(ShipL +11,ShipTop- 14);
	setPixel(ShipL +11,ShipTop- 13);
	setPixel(ShipL +11,ShipTop- 12);
	setPixel(ShipL +11,ShipTop- 11);
	setPixel(ShipL +11,ShipTop- 10);
	setPixel(ShipL +11,ShipTop- 9);
	//Eleventh Left Row
	setPixel(ShipL +12,ShipTop- 13);
	setPixel(ShipL +12,ShipTop- 12);
	setPixel(ShipL +12,ShipTop- 11);
	setPixel(ShipL +12,ShipTop- 10);
	setPixel(ShipL +12,ShipTop- 9);
	setPixel(ShipL +12,ShipTop- 8);
	setPixel(ShipL +12,ShipTop- 7);
	setPixel(ShipL +12,ShipTop- 6);
	setPixel(ShipL +12,ShipTop- 5);
	//Twelth Left Row
	setPixel(ShipL +13,ShipTop- 14);
	setPixel(ShipL +13,ShipTop- 13);
	setPixel(ShipL +13,ShipTop- 12);
	setPixel(ShipL +13,ShipTop- 11);
	//Thirteenth Left Rw
	setPixel(ShipL +14,ShipTop- 15);
	setPixel(ShipL +14,ShipTop- 14);
	setPixel(ShipL +14,ShipTop- 13);
	setPixel(ShipL +14,ShipTop- 12);
	//Fourteenth Left Row
	setPixel(ShipL +15,ShipTop- 16);
	setPixel(ShipL +15,ShipTop- 15);
	setPixel(ShipL +15,ShipTop- 14);
	setPixel(ShipL +15,ShipTop- 13);
	//Fifteenth Left Row
	setPixel(ShipL +16,ShipTop- 18);
	setPixel(ShipL +16,ShipTop- 17);
	setPixel(ShipL +16,ShipTop- 16);
	setPixel(ShipL +16,ShipTop- 15);
	setPixel(ShipL +16,ShipTop- 14);
	setPixel(ShipL +16,ShipTop- 13);
	setPixel(ShipL +16,ShipTop- 12);
	setPixel(ShipL +16,ShipTop- 11);
	setPixel(ShipL +16,ShipTop- 10);
	setPixel(ShipL +16,ShipTop- 9);
	setPixel(ShipL +16,ShipTop- 8);
	//Sixteenth Left Row

}
task main()
{
	ShipTop = 30;
	ShipL = 30;
	resetGyro(Gyro1);
	resetGyro(Gyro2);
	while(true)
	{
		if (getGyroDegrees(Gyro1) < 45 || getGyroDegrees(Gyro1) > 315) {
   Ship(ShipTop, ShipL);
   Ship(ShipTop + 20, ShipL + 30);
			} else if (getGyroDegrees(Gyro1) < 135 || getGyroDegrees(Gyro1) > 45) {
      Missile( 20,20);
      Missile( 40,40);
			} else if (getGyroDegrees(Gyro1) <225  || getGyroDegrees(Gyro1) > 135) {
     EMissile( 40, 20);
     EMissile( 50, 20);
     EMissile( 30, 20);
     EMissile( 20, 20);
			} else if (getGyroDegrees(Gyro1) <315  || getGyroDegrees(Gyro1) > 225) {
     Missile( 20,20);
     Ship( 40,40);
     EMissile(60,40);
		}


	}
}
